### PR TITLE
Change to Opheim simplification

### PR DESCRIPTION
**Pull request by widdma**
This changes the Visvalingam simplification in `cleanfigure` to a modified version of Opheim simplification. This resolves the issue @okomarov noticed in #585 

This also removes the pixelation routine for the general case. It is no longer required for the performance boost and Opheim simplification can be considered a generalization of this procedure. It is, however, still performed in the case where the line has markers and no further simplification is applied.

### CODE REVIEW

**Comment by PeterPablo** [comment]
@widdma, could you please merge `develop`? What needs to be done to get this merged? (@egeerardyn, @okomarov)

**Comment by okomarov** [comment]
I can do that. I also wanted to edit a bit the help text. 

Graphically and performance wise it works well.

**Comment by PeterPablo** [comment]
@okomarov, I actually tried this myself but didn't know how to force push to this PR?! I am currently using the branch and didn't spot any misbehavior yet.

**Comment by okomarov** [comment]
@PeterPablo You can merge current PR into line-simp branch, do the changes there.

**Pull request merged**
