### PR TITLE
Line simp

### PR DESCRIPTION
**Pull request by okomarov**
As already mentioned, graphically and performance wise is good. Just needs hashes.

### CODE REVIEW

**Comment by PeterPablo** [comment]
R2014 fails:
`           ACID( 74) herrorbarPlot            : hash                                  != (c3e1e86cf3abd40b6f3e61fa4787c804)  m2t failed`
This needs to be investigated.

**Comment by okomarov** [comment]
I already checked the visual output immediately after opheim algo was introduced.

**Comment by PeterPablo** [comment]
Thanks. Does ACID(74) work for you on HG1?

**Comment by okomarov** [comment]
It works for R2008a but fails on Octave.

**Comment by PeterPablo** [comment]
Something is fishy. I again checked out this PR and my octave is running fine -- Travis is failing though?!
My R2014a gives an error -- your R2008 doesn't?!

```
Error using matlab2tikz>drawErrorBars (line 3770)
Sizes of and error data not matching (6*2 ~= 89 and 6*89 ~= 2, 9*2-1 ~= 89, 9*89-1 ~= 2).

Error in matlab2tikz>drawHggroup (line 2426)
            [m2t,str] = drawErrorBars(m2t, h);

Error in matlab2tikz>handleAllChildren (line 657)
                [m2t, str] = drawHggroup(m2t, child);

Error in matlab2tikz>drawAxes (line 849)
    [m2t, childrenEnvs] = handleAllChildren(m2t, handle);

Error in matlab2tikz>saveToFile (line 450)
        m2t = drawAxes(m2t, relevantAxesHandle);

Error in matlab2tikz (line 352)
saveToFile(m2t, fid, fileWasOpen);
```

**Comment by okomarov** [comment]
It does error, my previous statement is incorrect. The problem lies in the simplification of errorbar series.

There two courses of action:
* Do not simplify errorbars series in cleanfigure
* Modify drawErrorbar to use lower/upper data instead of legacy code (this can be done for R2014a and not sure why it says it cannot, but probably not in Octave?).

**Comment by PeterPablo** [comment]
Which approach do you suggest? 1 sound easier. We could go with that and open a ticket for 2 to improve the cleanfigure behavior on errorbars in a later release?!

**Comment by okomarov** [comment]
The first one :). 

The second approach is already there for R2014b and I checked it should be viable for R2014a too (not sure why it is not used). However, dunno what Octave is using.

**Comment by PeterPablo** [comment]
It would be great, if you could add this commit -- permitting you have that much time at your disposal.

**Comment by okomarov** [comment]
Actually, neither solutions will work for Octave and hence I would now gor for solution 2 which is just as easy as deleting the whole legacy code for HG1. The HG2 implementation, is only 4 lines and works up until R2008a. Note that Octave does not reach that function at all, since it cannot detect the type (it's and hggroup).

Hence, I propose to delete legacy code, leave Octave as is (with error) and merge this PR.

To solve Octave's problem, we need `guessOctaveType()` function in `drawHggroup` that infers the type from try/catching properties unique to certain plots, e.g. `udata` should only be in errorbarseries.

**Comment by PeterPablo** [comment]
Sounds reasonable. Fine by me. Please add a comment in the code and ideally link to an issue or the comment of yours.

**Comment by PeterPablo** [comment]
The last few commits do:
* incorporate current tip of `develop`
* cherry-pick #655 to fix herrorbarplot in octave
* adapt `herrorbarPlot` (ACID(74)) to have changing horizontal/vertical deviations
* simplify handling of errorbars, as suggested by @okomarov 
* update hashes

Status:
* octave: ok
* R2014a: ok
* R2014b: Recheck, whether missing annotations in 87,89 are caused by this PR

**Comment by PeterPablo** [comment]
**Travis fails:**
```
--- <mine>/matlab2tikz/test/data/converted/test79-converted.tex
+++ (clipboard)
@@ -84,7 +84,8 @@
 0.909091	0.826446\\
 0.929293	0.863585\\
 0.949495	0.901541\\
-0.979798	0.960004\\
+0.969697	0.940312\\
+0.989899	0.9799\\
    1	   1\\
 };
 \addlegendentry{2};



--- <mine>/matlab2tikz/test/data/converted/test97-converted.tex
+++ (clipboard)
@@ -270,6 +270,7 @@
  240	0.672849\\
  241	0.475538\\
  242	0.250404\\
+ 243	0.0106193\\
  244	-0.229787\\
  245	-0.456748\\
  246	-0.656986\\
```

My local octave seems to behave differently, concerning the simplification of lines. I had the impression the `rand` calls present at an early stage were removed?! Subsequent local runs yield the same hashes, which indicates this is yet another *environment* issue we have to deal with. **Ideas?**

**Comment by PeterPablo** [comment]
The last commit that reduces `targetResolution` didn't help, though certainly affects the diff:
```
--- <mine>/matlab2tikz/test/data/converted/test97-converted.tex
+++ (clipboard)
@@ -61,6 +61,7 @@
   33	0.617442\\
   34	0.410506\\
   35	0.179552\\
+  36	-0.0619074\\
   37	-0.299744\\
   38	-0.520044\\
   39	-0.709917\\
@@ -73,6 +74,7 @@
   46	-0.609054\\
   47	-0.400799\\
   48	-0.169095\\
+  49	0.0725028\\
   50	0.309859\\
   51	0.529085\\
   52	0.717356\\
@@ -188,6 +190,8 @@
  162	0.718588\\
  163	0.530586\\
  164	0.311541\\
+ 165	0.0742678\\
+ 166	-0.16735\\
  167	-0.399177\\
  168	-0.607649\\
  169	-0.780569\\
@@ -199,6 +203,8 @@
  175	-0.711162\\
  176	-0.521555\\
  177	-0.301432\\
+ 178	-0.0636737\\
+ 179	0.177811\\
  180	0.408891\\
  181	0.616049\\
  182	0.787163\\
@@ -320,6 +326,7 @@
   33	0.617442\\
   34	0.410506\\
   35	0.179552\\
+  36	-0.0619074\\
   37	-0.299744\\
   38	-0.520044\\
   39	-0.709917\\
@@ -332,6 +339,7 @@
   46	-0.609054\\
   47	-0.400799\\
   48	-0.169095\\
+  49	0.0725028\\
   50	0.309859\\
   51	0.529085\\
   52	0.717356\\
@@ -395,6 +403,7 @@
   33	0.617442\\
   34	0.410506\\
   35	0.179552\\
+  36	-0.0619074\\
   37	-0.299744\\
   38	-0.520044\\
   39	-0.709917\\
@@ -407,6 +416,7 @@
   46	-0.609054\\
   47	-0.400799\\
   48	-0.169095\\
+  49	0.0725028\\
   50	0.309859\\
   51	0.529085\\
   52	0.717356\\
@@ -471,6 +481,7 @@
   33	0.617442\\
   34	0.410506\\
   35	0.179552\\
+  36	-0.0619074\\
   37	-0.299744\\
   38	-0.520044\\
   39	-0.709917\\
@@ -483,6 +494,7 @@
   46	-0.609054\\
   47	-0.400799\\
   48	-0.169095\\
+  49	0.0725028\\
   50	0.309859\\
   51	0.529085\\
   52	0.717356\\
```
May be #641 could come to rescue? Ideas?

**Comment by PeterPablo** [comment]
**Update:** I figured out a way to make the tests reliable. Short version: `W` and `H` are determined differently on different environments by `getWidthHeightInPixels()`.
I refrained from force-pushing and thus opened #660 as a clean PR, though theoretically I can also continue here. @egeerardyn, please advise (at least a7579ed would have to be reverted).

**Comment by egeerardyn** [comment]
@PeterPablo Sorry for the late answer. I would say that force-pushing is a feature that should be avoided (unless you are 99% sure that nothing bad can happen, but most of the time it's the same story as rebasing: if nobody has seen the affected branch, it might be fine, but it's better avoided, certainly if the code has been out there for a while).

**Comment by PeterPablo** [comment]
Understood by now. Thanks for getting back anyhow.

**Comment by PeterPablo** [comment]
Let me add: That's why I went with opening a new clean branch...

**Pull request closed without merging**
