### PR TITLE
Another round of refactorings

### PR DESCRIPTION
**Pull request by egeerardyn**
I've spent my Sunday refactoring some parts, mainly to address #391, but also some other things that have been bothering me for a while. Note that since everything should be a refactoring, no additional functionality has been included.

* I've added a `FIXME` tag in ee9a811 where we can change the Z-order of the axes/grids/... (I have been dragging that commit along for a bit too long now, I thought it was time to incorporate it)
* All functions should now use the `opts_*` internal API for option arrays.
* As a side result, I've also added some functions to convert to/from option array and plain cell arrays with `{'key=value', 'key', ...}` syntax (i.e. legacy format for options).
* Complexity has been reduced from 97 to 27 as in the overview below:

       Function       |Complexity 
----------------------|-----------
`shaderOptsSurfPatch` |    14     
  `drawScatterPlot`   |    13     
      **Total**       |    27     

complexity

> **Little factoid**: the complexity peak at `2` in the figure above is due to a common pattern I've been using in some functions, i.e.
> ```matlab
> function [...] = X(...)
>    if flag
>       % do X
>    end
> end
> ```

Everything works in our R2014b ACID test, hopefully Travis agrees for Octave. There are, however, some parts, that I'm not entirely happy with (especially  5947e03), but it is a step in the right direction.

I might work a bit further on this PR over the next week, but feel free to share your comments (or even merge this PR) in the meanwhile.

### CODE REVIEW

**Comment by PeterPablo** [comment]
@egeerardyn, your changes look good to me and certainly help simplifying matters!
Unfortunately octave has one failing test (see also travis) and R2014b has another one:
`ACID( 97) overlappingPlots         : hash 6676eab27a2f547980ecd4c838350211 != (9a2846d13fb2f378c7b904066e8136d5)`
As soon as those are resolved or determined to be ok, feel free to merge.

**Comment by egeerardyn** [comment]
@PeterPablo Could you paste the output produced for `ACID(97)` because here it reproduces fine on R2014b. Maybe this is just an unreliable test?

**Comment by PeterPablo** [comment]
I just noticed that `ACID(97)` gives the same "wrong" hash on current `develop`. May be again due to `width`, `height` and/or `at` being slightly of?

Anyhow, as requested:
```
% This file was created by matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\definecolor{mycolor1}{rgb}{0.00000,0.44700,0.74100}%
%
\begin{tikzpicture}

\begin{axis}[%
width=0.870786\figurewidth,
height=0.91573\figureheight,
at={(0\figurewidth,0\figureheight)},
scale only axis,
xmin=       1,
xmax=     256,
ymin=      -1,
ymax=       1,
axis background/.style={fill=white}
]
\addplot [color=mycolor1,solid,forget plot]
  table[row sep=crcr]{%
       1	0.841471\\
       2	0.946586\\
       3	0.996318\\
       4	0.987757\\
       5	0.921405\\
       6	0.801143\\
       7	0.634008\\
       8	0.429779\\
       9	0.200404\\
      10	-0.0406968\\
      11	-0.279416\\
      12	-0.501787\\
      13	 -0.6948\\
      14	-0.847161\\
      15	-0.949957\\
      16	-0.997172\\
      17	-0.986045\\
      18	-0.917227\\
      19	-0.794743\\
      20	-0.62576\\
      21	-0.420166\\
      22	-0.189988\\
      23	0.051305\\
      24	0.289597\\
      25	0.510945\\
      26	0.702398\\
      27	0.852756\\
      28	 0.95322\\
      29	0.997914\\
      30	0.984222\\
      31	0.912945\\
      32	0.788253\\
      33	0.617442\\
      34	0.410506\\
      35	0.179552\\
      36	-0.0619074\\
      37	-0.299744\\
      38	-0.520044\\
      39	-0.709917\\
      40	-0.858254\\
      41	-0.956377\\
      42	-0.998543\\
      43	-0.982287\\
      44	-0.90856\\
      45	-0.781674\\
      46	-0.609054\\
      47	-0.400799\\
      48	-0.169095\\
      49	0.0725028\\
      50	0.309859\\
      51	0.529085\\
      52	0.717356\\
      53	0.863656\\
      54	0.959425\\
      55	 0.99906\\
      56	0.980242\\
      57	0.904072\\
      58	0.775007\\
      59	0.600597\\
      60	0.391048\\
      61	0.158619\\
      62	-0.08309\\
      63	-0.319938\\
      64	-0.538067\\
      65	-0.724714\\
      66	-0.86896\\
      67	-0.962365\\
      68	-0.999464\\
      69	-0.978086\\
      70	-0.899483\\
      71	-0.768252\\
      72	-0.592073\\
      73	-0.381252\\
      74	-0.148125\\
      75	0.0936679\\
      76	0.329981\\
      77	0.546987\\
      78	 0.73199\\
      79	0.874166\\
      80	0.965197\\
      81	0.999755\\
      82	 0.97582\\
      83	0.894792\\
      84	0.761411\\
      85	0.583481\\
      86	0.371413\\
      87	0.137615\\
      88	-0.104235\\
      89	-0.339987\\
      90	-0.555846\\
      91	-0.739184\\
      92	-0.879274\\
      93	-0.96792\\
      94	-0.999934\\
      95	-0.973444\\
      96	   -0.89\\
      97	-0.754484\\
      98	-0.574824\\
      99	-0.361533\\
     100	-0.127089\\
     101	0.114791\\
     102	0.349954\\
     103	0.564642\\
     104	0.746295\\
     105	0.884283\\
     106	0.970533\\
     107	       1\\
     108	0.970958\\
     109	0.885108\\
     110	0.747472\\
     111	0.566102\\
     112	0.351611\\
     113	0.116549\\
     114	-0.125333\\
     115	-0.359882\\
     116	-0.573375\\
     117	-0.753321\\
     118	-0.889192\\
     119	-0.973037\\
     120	-0.999953\\
     121	-0.968363\\
     122	-0.880116\\
     123	-0.740375\\
     124	-0.557317\\
     125	-0.34165\\
     126	-0.105995\\
     127	0.135862\\
     128	 0.36977\\
     129	0.582043\\
     130	0.760262\\
     131	   0.894\\
     132	0.975432\\
     133	0.999793\\
     134	0.965658\\
     135	0.875025\\
     136	0.733195\\
     137	0.548468\\
     138	0.331651\\
     139	0.0954297\\
     140	-0.146375\\
     141	-0.379615\\
     142	-0.590645\\
     143	-0.767118\\
     144	-0.898708\\
     145	-0.977716\\
     146	-0.99952\\
     147	-0.962845\\
     148	-0.869835\\
     149	-0.725933\\
     150	-0.539557\\
     151	-0.321614\\
     152	-0.0848536\\
     153	0.156872\\
     154	0.389418\\
     155	0.599181\\
     156	0.773887\\
     157	0.903314\\
     158	 0.97989\\
     159	0.999135\\
     160	0.959922\\
     161	0.864547\\
     162	0.718588\\
     163	0.530586\\
     164	0.311541\\
     165	0.0742678\\
     166	-0.16735\\
     167	-0.399177\\
     168	-0.607649\\
     169	-0.780569\\
     170	-0.907819\\
     171	-0.981954\\
     172	-0.998637\\
     173	-0.956892\\
     174	-0.859161\\
     175	-0.711162\\
     176	-0.521555\\
     177	-0.301432\\
     178	-0.0636737\\
     179	0.177811\\
     180	0.408891\\
     181	0.616049\\
     182	0.787163\\
     183	0.912221\\
     184	0.983907\\
     185	0.998027\\
     186	0.953754\\
     187	0.853679\\
     188	0.703657\\
     189	0.512465\\
     190	 0.29129\\
     191	0.0530724\\
     192	-0.188251\\
     193	-0.418559\\
     194	-0.624379\\
     195	-0.793668\\
     196	-0.91652\\
     197	-0.985749\\
     198	-0.997304\\
     199	-0.950508\\
     200	 -0.8481\\
     201	-0.696072\\
     202	-0.503317\\
     203	-0.281115\\
     204	-0.0424651\\
     205	0.198669\\
     206	 0.42818\\
     207	0.632639\\
     208	0.800083\\
     209	0.920716\\
     210	 0.98748\\
     211	0.996468\\
     212	0.947155\\
     213	0.842426\\
     214	0.688408\\
     215	0.494113\\
     216	0.270908\\
     217	0.031853\\
     218	-0.209066\\
     219	-0.437752\\
     220	-0.640827\\
     221	-0.806408\\
     222	-0.924808\\
     223	-0.989099\\
     224	-0.99552\\
     225	-0.943695\\
     226	-0.836657\\
     227	-0.680667\\
     228	-0.484853\\
     229	-0.260671\\
     230	-0.0212373\\
     231	0.219439\\
     232	0.447275\\
     233	0.648943\\
     234	0.812643\\
     235	0.928796\\
     236	0.990607\\
     237	 0.99446\\
     238	0.940129\\
     239	0.830793\\
     240	0.672849\\
     241	0.475538\\
     242	0.250404\\
     243	0.0106193\\
     244	-0.229787\\
     245	-0.456748\\
     246	-0.656986\\
     247	-0.818785\\
     248	-0.932679\\
     249	-0.992003\\
     250	-0.993288\\
     251	-0.936457\\
     252	-0.824836\\
     253	-0.664955\\
     254	-0.466169\\
     255	-0.240109\\
     256	-2.44929e-15\\
};
\end{axis}

\begin{axis}[%
width=0.337079\figurewidth,
height=0.449438\figureheight,
at={(0.078652\figurewidth,0.550562\figureheight)},
scale only axis,
xmin=       1,
xmax=      64,
ymin=      -1,
ymax=       1,
axis background/.style={fill=green}
]
\addplot [color=black,solid,forget plot]
  table[row sep=crcr]{%
       1	0.841471\\
       2	0.946586\\
       3	0.996318\\
       4	0.987757\\
       5	0.921405\\
       6	0.801143\\
       7	0.634008\\
       8	0.429779\\
       9	0.200404\\
      10	-0.0406968\\
      11	-0.279416\\
      12	-0.501787\\
      13	 -0.6948\\
      14	-0.847161\\
      15	-0.949957\\
      16	-0.997172\\
      17	-0.986045\\
      18	-0.917227\\
      19	-0.794743\\
      20	-0.62576\\
      21	-0.420166\\
      22	-0.189988\\
      23	0.051305\\
      24	0.289597\\
      25	0.510945\\
      26	0.702398\\
      27	0.852756\\
      28	 0.95322\\
      29	0.997914\\
      30	0.984222\\
      31	0.912945\\
      32	0.788253\\
      33	0.617442\\
      34	0.410506\\
      35	0.179552\\
      36	-0.0619074\\
      37	-0.299744\\
      38	-0.520044\\
      39	-0.709917\\
      40	-0.858254\\
      41	-0.956377\\
      42	-0.998543\\
      43	-0.982287\\
      44	-0.90856\\
      45	-0.781674\\
      46	-0.609054\\
      47	-0.400799\\
      48	-0.169095\\
      49	0.0725028\\
      50	0.309859\\
      51	0.529085\\
      52	0.717356\\
      53	0.863656\\
      54	0.959425\\
      55	 0.99906\\
      56	0.980242\\
      57	0.904072\\
      58	0.775007\\
      59	0.600597\\
      60	0.391048\\
      61	0.158619\\
      62	-0.08309\\
      63	-0.319938\\
      64	-0.538067\\
};
\end{axis}

\begin{axis}[%
width=0.224719\figurewidth,
height=0.449438\figureheight,
at={(0.640449\figurewidth,0.101124\figureheight)},
scale only axis,
xmin=       0,
xmax=     100,
ymin=      -1,
ymax=       1
]
\addplot [color=black,solid,forget plot]
  table[row sep=crcr]{%
       1	0.841471\\
       2	0.946586\\
       3	0.996318\\
       4	0.987757\\
       5	0.921405\\
       6	0.801143\\
       7	0.634008\\
       8	0.429779\\
       9	0.200404\\
      10	-0.0406968\\
      11	-0.279416\\
      12	-0.501787\\
      13	 -0.6948\\
      14	-0.847161\\
      15	-0.949957\\
      16	-0.997172\\
      17	-0.986045\\
      18	-0.917227\\
      19	-0.794743\\
      20	-0.62576\\
      21	-0.420166\\
      22	-0.189988\\
      23	0.051305\\
      24	0.289597\\
      25	0.510945\\
      26	0.702398\\
      27	0.852756\\
      28	 0.95322\\
      29	0.997914\\
      30	0.984222\\
      31	0.912945\\
      32	0.788253\\
      33	0.617442\\
      34	0.410506\\
      35	0.179552\\
      36	-0.0619074\\
      37	-0.299744\\
      38	-0.520044\\
      39	-0.709917\\
      40	-0.858254\\
      41	-0.956377\\
      42	-0.998543\\
      43	-0.982287\\
      44	-0.90856\\
      45	-0.781674\\
      46	-0.609054\\
      47	-0.400799\\
      48	-0.169095\\
      49	0.0725028\\
      50	0.309859\\
      51	0.529085\\
      52	0.717356\\
      53	0.863656\\
      54	0.959425\\
      55	 0.99906\\
      56	0.980242\\
      57	0.904072\\
      58	0.775007\\
      59	0.600597\\
      60	0.391048\\
      61	0.158619\\
      62	-0.08309\\
      63	-0.319938\\
      64	-0.538067\\
};
\end{axis}

\begin{axis}[%
width=0.337079\figurewidth,
height=0.449438\figureheight,
at={(0.134831\figurewidth,0.213483\figureheight)},
scale only axis,
xmin=       0,
xmax=     100,
ymin=      -1,
ymax=       1,
axis background/.style={fill=white}
]
\addplot [color=red,solid,forget plot]
  table[row sep=crcr]{%
       1	0.841471\\
       2	0.946586\\
       3	0.996318\\
       4	0.987757\\
       5	0.921405\\
       6	0.801143\\
       7	0.634008\\
       8	0.429779\\
       9	0.200404\\
      10	-0.0406968\\
      11	-0.279416\\
      12	-0.501787\\
      13	 -0.6948\\
      14	-0.847161\\
      15	-0.949957\\
      16	-0.997172\\
      17	-0.986045\\
      18	-0.917227\\
      19	-0.794743\\
      20	-0.62576\\
      21	-0.420166\\
      22	-0.189988\\
      23	0.051305\\
      24	0.289597\\
      25	0.510945\\
      26	0.702398\\
      27	0.852756\\
      28	 0.95322\\
      29	0.997914\\
      30	0.984222\\
      31	0.912945\\
      32	0.788253\\
      33	0.617442\\
      34	0.410506\\
      35	0.179552\\
      36	-0.0619074\\
      37	-0.299744\\
      38	-0.520044\\
      39	-0.709917\\
      40	-0.858254\\
      41	-0.956377\\
      42	-0.998543\\
      43	-0.982287\\
      44	-0.90856\\
      45	-0.781674\\
      46	-0.609054\\
      47	-0.400799\\
      48	-0.169095\\
      49	0.0725028\\
      50	0.309859\\
      51	0.529085\\
      52	0.717356\\
      53	0.863656\\
      54	0.959425\\
      55	 0.99906\\
      56	0.980242\\
      57	0.904072\\
      58	0.775007\\
      59	0.600597\\
      60	0.391048\\
      61	0.158619\\
      62	-0.08309\\
      63	-0.319938\\
      64	-0.538067\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

**Comment by egeerardyn** [comment]
I still have to inspect `ACID(97)` in detail before this can be merged.

**Comment by egeerardyn** [comment]
Difference between our `ACID(97)` output is:

```diff
% This file was created by matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\definecolor{mycolor1}{rgb}{0.00000,0.44700,0.74100}%
%
\begin{tikzpicture}

\begin{axis}[%
width=0.870786\figurewidth,
height=0.91573\figureheight,
at={(0\figurewidth,0\figureheight)},
scale only axis,
xmin=       1,
xmax=     256,
ymin=      -1,
ymax=       1,
axis background/.style={fill=white}
]
\addplot [color=mycolor1,solid,forget plot]
  table[row sep=crcr]{%
       1    0.841471\\
       2    0.946586\\
       3    0.996318\\
       4    0.987757\\
       5    0.921405\\
       6    0.801143\\
       7    0.634008\\
       8    0.429779\\
       9    0.200404\\
      10    -0.0406968\\
      11    -0.279416\\
      12    -0.501787\\
      13     -0.6948\\
      14    -0.847161\\
      15    -0.949957\\
      16    -0.997172\\
      17    -0.986045\\
      18    -0.917227\\
      19    -0.794743\\
      20    -0.62576\\
      21    -0.420166\\
      22    -0.189988\\
      23    0.051305\\
      24    0.289597\\
      25    0.510945\\
      26    0.702398\\
      27    0.852756\\
      28     0.95322\\
      29    0.997914\\
      30    0.984222\\
      31    0.912945\\
      32    0.788253\\
      33    0.617442\\
      34    0.410506\\
      35    0.179552\\
      36    -0.0619074\\
      37    -0.299744\\
      38    -0.520044\\
      39    -0.709917\\
      40    -0.858254\\
      41    -0.956377\\
      42    -0.998543\\
      43    -0.982287\\
      44    -0.90856\\
      45    -0.781674\\
      46    -0.609054\\
      47    -0.400799\\
      48    -0.169095\\
      49    0.0725028\\
      50    0.309859\\
      51    0.529085\\
      52    0.717356\\
      53    0.863656\\
      54    0.959425\\
      55     0.99906\\
      56    0.980242\\
      57    0.904072\\
      58    0.775007\\
      59    0.600597\\
      60    0.391048\\
      61    0.158619\\
      62    -0.08309\\
      63    -0.319938\\
      64    -0.538067\\
      65    -0.724714\\
      66    -0.86896\\
      67    -0.962365\\
      68    -0.999464\\
      69    -0.978086\\
      70    -0.899483\\
      71    -0.768252\\
      72    -0.592073\\
      73    -0.381252\\
      74    -0.148125\\
      75    0.0936679\\
      76    0.329981\\
      77    0.546987\\
      78     0.73199\\
      79    0.874166\\
      80    0.965197\\
      81    0.999755\\
      82     0.97582\\
      83    0.894792\\
      84    0.761411\\
      85    0.583481\\
      86    0.371413\\
      87    0.137615\\
      88    -0.104235\\
      89    -0.339987\\
      90    -0.555846\\
      91    -0.739184\\
      92    -0.879274\\
      93    -0.96792\\
      94    -0.999934\\
      95    -0.973444\\
      96       -0.89\\
      97    -0.754484\\
      98    -0.574824\\
      99    -0.361533\\
     100    -0.127089\\
     101    0.114791\\
     102    0.349954\\
     103    0.564642\\
     104    0.746295\\
     105    0.884283\\
     106    0.970533\\
     107           1\\
     108    0.970958\\
     109    0.885108\\
     110    0.747472\\
     111    0.566102\\
     112    0.351611\\
     113    0.116549\\
     114    -0.125333\\
     115    -0.359882\\
     116    -0.573375\\
     117    -0.753321\\
     118    -0.889192\\
     119    -0.973037\\
     120    -0.999953\\
     121    -0.968363\\
     122    -0.880116\\
     123    -0.740375\\
     124    -0.557317\\
     125    -0.34165\\
     126    -0.105995\\
     127    0.135862\\
     128     0.36977\\
     129    0.582043\\
     130    0.760262\\
     131       0.894\\
     132    0.975432\\
     133    0.999793\\
     134    0.965658\\
     135    0.875025\\
     136    0.733195\\
     137    0.548468\\
     138    0.331651\\
     139    0.0954297\\
     140    -0.146375\\
     141    -0.379615\\
     142    -0.590645\\
     143    -0.767118\\
     144    -0.898708\\
     145    -0.977716\\
     146    -0.99952\\
     147    -0.962845\\
     148    -0.869835\\
     149    -0.725933\\
     150    -0.539557\\
     151    -0.321614\\
     152    -0.0848536\\
     153    0.156872\\
     154    0.389418\\
     155    0.599181\\
     156    0.773887\\
     157    0.903314\\
     158     0.97989\\
     159    0.999135\\
     160    0.959922\\
     161    0.864547\\
     162    0.718588\\
     163    0.530586\\
     164    0.311541\\
     165    0.0742678\\
     166    -0.16735\\
     167    -0.399177\\
     168    -0.607649\\
     169    -0.780569\\
     170    -0.907819\\
     171    -0.981954\\
     172    -0.998637\\
     173    -0.956892\\
     174    -0.859161\\
     175    -0.711162\\
     176    -0.521555\\
     177    -0.301432\\
     178    -0.0636737\\
     179    0.177811\\
     180    0.408891\\
     181    0.616049\\
     182    0.787163\\
     183    0.912221\\
     184    0.983907\\
     185    0.998027\\
     186    0.953754\\
     187    0.853679\\
     188    0.703657\\
     189    0.512465\\
     190     0.29129\\
     191    0.0530724\\
     192    -0.188251\\
     193    -0.418559\\
     194    -0.624379\\
     195    -0.793668\\
     196    -0.91652\\
     197    -0.985749\\
     198    -0.997304\\
     199    -0.950508\\
     200     -0.8481\\
     201    -0.696072\\
     202    -0.503317\\
     203    -0.281115\\
     204    -0.0424651\\
     205    0.198669\\
     206     0.42818\\
     207    0.632639\\
     208    0.800083\\
     209    0.920716\\
     210     0.98748\\
     211    0.996468\\
     212    0.947155\\
     213    0.842426\\
     214    0.688408\\
     215    0.494113\\
     216    0.270908\\
     217    0.031853\\
     218    -0.209066\\
     219    -0.437752\\
     220    -0.640827\\
     221    -0.806408\\
     222    -0.924808\\
     223    -0.989099\\
     224    -0.99552\\
     225    -0.943695\\
     226    -0.836657\\
     227    -0.680667\\
     228    -0.484853\\
     229    -0.260671\\
     230    -0.0212373\\
     231    0.219439\\
     232    0.447275\\
     233    0.648943\\
     234    0.812643\\
     235    0.928796\\
     236    0.990607\\
     237     0.99446\\
     238    0.940129\\
     239    0.830793\\
     240    0.672849\\
     241    0.475538\\
     242    0.250404\\
     243    0.0106193\\
     244    -0.229787\\
     245    -0.456748\\
     246    -0.656986\\
     247    -0.818785\\
     248    -0.932679\\
     249    -0.992003\\
     250    -0.993288\\
     251    -0.936457\\
     252    -0.824836\\
     253    -0.664955\\
     254    -0.466169\\
     255    -0.240109\\
     256    -2.44929e-15\\
};
\end{axis}

\begin{axis}[%
width=0.337079\figurewidth,
height=0.449438\figureheight,
at={(0.078652\figurewidth,0.550562\figureheight)},
scale only axis,
xmin=       1,
xmax=      64,
ymin=      -1,
ymax=       1,
axis background/.style={fill=green}
]
\addplot [color=black,solid,forget plot]
  table[row sep=crcr]{%
       1    0.841471\\
       2    0.946586\\
       3    0.996318\\
       4    0.987757\\
       5    0.921405\\
       6    0.801143\\
       7    0.634008\\
       8    0.429779\\
       9    0.200404\\
      10    -0.0406968\\
      11    -0.279416\\
      12    -0.501787\\
      13     -0.6948\\
      14    -0.847161\\
      15    -0.949957\\
      16    -0.997172\\
      17    -0.986045\\
      18    -0.917227\\
      19    -0.794743\\
      20    -0.62576\\
      21    -0.420166\\
      22    -0.189988\\
      23    0.051305\\
      24    0.289597\\
      25    0.510945\\
      26    0.702398\\
      27    0.852756\\
      28     0.95322\\
      29    0.997914\\
      30    0.984222\\
      31    0.912945\\
      32    0.788253\\
      33    0.617442\\
      34    0.410506\\
      35    0.179552\\
      36    -0.0619074\\
      37    -0.299744\\
      38    -0.520044\\
      39    -0.709917\\
      40    -0.858254\\
      41    -0.956377\\
      42    -0.998543\\
      43    -0.982287\\
      44    -0.90856\\
      45    -0.781674\\
      46    -0.609054\\
      47    -0.400799\\
      48    -0.169095\\
      49    0.0725028\\
      50    0.309859\\
      51    0.529085\\
      52    0.717356\\
      53    0.863656\\
      54    0.959425\\
      55     0.99906\\
      56    0.980242\\
      57    0.904072\\
      58    0.775007\\
      59    0.600597\\
      60    0.391048\\
      61    0.158619\\
      62    -0.08309\\
      63    -0.319938\\
      64    -0.538067\\
};
\end{axis}

\begin{axis}[%
width=0.224719\figurewidth,
height=0.449438\figureheight,
at={(0.640449\figurewidth,0.101124\figureheight)},
scale only axis,
xmin=       0,
xmax=     100,
ymin=      -1,
ymax=       1
]
\addplot [color=black,solid,forget plot]
  table[row sep=crcr]{%
       1    0.841471\\
       2    0.946586\\
       3    0.996318\\
       4    0.987757\\
       5    0.921405\\
       6    0.801143\\
       7    0.634008\\
       8    0.429779\\
       9    0.200404\\
      10    -0.0406968\\
      11    -0.279416\\
      12    -0.501787\\
      13     -0.6948\\
      14    -0.847161\\
      15    -0.949957\\
      16    -0.997172\\
      17    -0.986045\\
      18    -0.917227\\
      19    -0.794743\\
      20    -0.62576\\
      21    -0.420166\\
      22    -0.189988\\
      23    0.051305\\
      24    0.289597\\
      25    0.510945\\
      26    0.702398\\
      27    0.852756\\
      28     0.95322\\
      29    0.997914\\
      30    0.984222\\
      31    0.912945\\
      32    0.788253\\
      33    0.617442\\
      34    0.410506\\
      35    0.179552\\
      36    -0.0619074\\
      37    -0.299744\\
      38    -0.520044\\
      39    -0.709917\\
      40    -0.858254\\
      41    -0.956377\\
      42    -0.998543\\
      43    -0.982287\\
      44    -0.90856\\
      45    -0.781674\\
      46    -0.609054\\
      47    -0.400799\\
      48    -0.169095\\
      49    0.0725028\\
      50    0.309859\\
      51    0.529085\\
      52    0.717356\\
      53    0.863656\\
      54    0.959425\\
      55     0.99906\\
      56    0.980242\\
      57    0.904072\\
      58    0.775007\\
      59    0.600597\\
      60    0.391048\\
      61    0.158619\\
      62    -0.08309\\
      63    -0.319938\\
      64    -0.538067\\
};
\end{axis}

\begin{axis}[%
width=0.337079\figurewidth,
height=0.449438\figureheight,
at={(0.134831\figurewidth,0.213483\figureheight)},
scale only axis,
xmin=       0,
-xmax=      80,
+xmax=      100,
ymin=      -1,
ymax=       1,
axis background/.style={fill=white}
]
\addplot [color=red,solid,forget plot]
  table[row sep=crcr]{%
       1    0.841471\\
       2    0.946586\\
       3    0.996318\\
       4    0.987757\\
       5    0.921405\\
       6    0.801143\\
       7    0.634008\\
       8    0.429779\\
       9    0.200404\\
      10    -0.0406968\\
      11    -0.279416\\
      12    -0.501787\\
      13     -0.6948\\
      14    -0.847161\\
      15    -0.949957\\
      16    -0.997172\\
      17    -0.986045\\
      18    -0.917227\\
      19    -0.794743\\
      20    -0.62576\\
      21    -0.420166\\
      22    -0.189988\\
      23    0.051305\\
      24    0.289597\\
      25    0.510945\\
      26    0.702398\\
      27    0.852756\\
      28     0.95322\\
      29    0.997914\\
      30    0.984222\\
      31    0.912945\\
      32    0.788253\\
      33    0.617442\\
      34    0.410506\\
      35    0.179552\\
      36    -0.0619074\\
      37    -0.299744\\
      38    -0.520044\\
      39    -0.709917\\
      40    -0.858254\\
      41    -0.956377\\
      42    -0.998543\\
      43    -0.982287\\
      44    -0.90856\\
      45    -0.781674\\
      46    -0.609054\\
      47    -0.400799\\
      48    -0.169095\\
      49    0.0725028\\
      50    0.309859\\
      51    0.529085\\
      52    0.717356\\
      53    0.863656\\
      54    0.959425\\
      55     0.99906\\
      56    0.980242\\
      57    0.904072\\
      58    0.775007\\
      59    0.600597\\
      60    0.391048\\
      61    0.158619\\
      62    -0.08309\\
      63    -0.319938\\
      64    -0.538067\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

So this seems like the test, or rather our different MATLAB settings?, might cause the unreliability.

**Comment by PeterPablo** [comment]
It certainly is! I just checked it and we do not explicitly set the `xlim` of that axis object. My MATLAB 2014b seems to decide that 100 is the right choice for the red plot, whereas yours goes for 80. (The behavior does not change, even if I set `figureVisible` to `true`.)

R2014a:
image

R2014b:
image

This is unrelated to your PR.

**Comment by egeerardyn** [comment]
@PeterPablo I think we should indeed refrain from setting the limits if they have not been specified by the user. 
I wouldn't update the test code, since that changes the hash everywhere! Also, for your case, maybe you need to nudge it by 10%, for somebody else by 20%. The test is unreliable as it currently is, so that's the only thing we should do for the time being.

**Comment by PeterPablo** [comment]
I opened ticket #591 to discuss this further. Please go ahead and mark this test as unreliable.
Did you find out, why that other test had failed? (Travis is now green.)

**Comment by egeerardyn** [comment]
TODO:

 * [ ] [address naming/documentation of `showInLegend()`](https://github.com/egeerardyn/matlab2tikz/commit/7106d15bef7446de710cfddad5f088d70772e920)

**Pull request merged**
