### PR TITLE
improve behavior of testsuite on Windows octave

### PR DESCRIPTION
**Pull request by PeterPablo**
See https://github.com/matlab2tikz/matlab2tikz/pull/602 for discussion.

### CODE REVIEW

**Comment by PeterPablo** [comment]
@okomarov, could you please test this? If you agree, please go forward and merge. This change does not influence Travis, as it only matches Windows+Octave.

**Comment by okomarov** [comment]
It improves things quite a bit! From 13 unmatching to 7. No effect on the 27 unreliable ones.

**Comment by PeterPablo** [comment]
The other six match now? That is nice, considering this is such a minor change -- thanks to your investigation and `DIFF`ing.

**Comment by okomarov** [comment]
Yes, 6 hashes match now. I reckon the remaining 7 do not match due to numerical differences.

**Comment by PeterPablo** [comment]
Please go ahead and upload your output for one of the failing ones in the discussion of PR #604. Please choose a testcase with comparatively small output and once with the PR applied and once without.
PR #604 should solve numerical differences for numbers close to `eps`, though does NOT solve problems related to different figure dimensions (we need a separate solution).

**Pull request merged**
