### PR TITLE
TikZ code customization

### PR DESCRIPTION
**Pull request by egeerardyn**
This is a partial implementation of #393 and as discussed in #831 as well, this encompasses a more unified calling convention of the `draw*` functions.

I am releasing this as **experimental**, i.e. the code should not be merged yet! This is just for review and discussion. In due time, I will rebase this code on top of develop.

TODO:
- [ ] also add a field for custom file names, e.g. such that we can do "curve X" should end up in a file named `x.tsv` instead of `figure1.tsv`.

### CODE REVIEW

**Comment by egeerardyn** [comment]
Just FYI, I ran some timings on this PR as I expect a bit of a performance penalty: for every object for which we call `handleObject`, I basically build an `inputParser` to validate its custom data structure (i.e. I expect this to be quite slow, but it makes optimal use of pre-existing code and is very flexible).
screen shot 2015-12-09 at 10 37 53

From the figure, you can see that for most our test cases, there is a 10% performance penalty (which is less than I anticipated, so I'm quite happy with this). In any case, there are a few things we can try to speed this up a bit:
 - make the `inputParser` persistent
 - refactor `m2tcustom` such that it first checks in which mode it runs and only does the necessary work for each case. I suspect specifically handling the case `m2tcustom([])` may provide us with a decent speed-up already.

**Comment by miscco** [comment]
Thats more than i expected, as i will be traveling a lot for the rest of the month i doubt i will find too much time reviewing this approach, given the other PRs.

**Comment by egeerardyn** [comment]
Okay, I got rid of the performance penalty, I think (based on 5 repeated tests).
screen shot 2015-12-09 at 13 44 16

**Comment by egeerardyn** [comment]
@LJeub I have noticed that you have been working further on this feature on your own repo. If you have some comments for this branch, I would be very happy discuss them with you and make sure we can converge back again.

**Pull request merged**
