### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by egeerardyn**
Just some minor cleanup:
 - removed an unused function
 - fixed spacing in a function (it seems our automatic whitespace tool is a bit too coarse at the moment), I will have a look whether we can't make `git` do some things in a pre-commit hook to avoid at least trailing whitespace.

### CODE REVIEW

**Comment by miscco** [comment]
Seems obviously correct :+1:

**Comment by egeerardyn** [comment]
Thanks for checking!

**Comment by miscco** [comment]
Although i have to say, that I might use the addIfNotDefault function for the grid options. It seems rather handy, whenever one deals with coloring etc

**Comment by egeerardyn** [comment]
Feel free to revert that commit when you would want to use it :smile:

In the past, I wrote that function exactly for such purposes, but now that I think of it: there are actually only a few properties that can be converted 1:1 from MATLAB to TikZ. E.g. colors require additional translation (e.g. `[1 0 0 ]` to `'red'`), such that the function has very few actual use cases.

**Comment by miscco** [comment]
That is true, but it can be handy to check if it is the default value and only change it when not.

**Comment by egeerardyn** [comment]
@miscco That's why we have the `getAndCheckDefault`.
The function I removed, `addIfNotDefault`, was a wrapper around `getAndCheckDefault` that just added the MATLAB value to an OptionArray if the value was non-default. So it's less useful.

**Pull request merged**
