### PR TITLE
Fix image dimensions swapped

### LINKED ISSUE #713: Failure with imagesAsPng=false and vectors for xdata&ydata; fix included
The following code fails with current m2t-develop:
```matlab
figure; imagesc(1:4,1:8,zeros(8,4))
matlab2tikz('/tmp/test.tikz','imagesAsPng',false)
```
Error message
```
Error using matlab2tikz>imageAsTikZ (line 2165)
Array lengths not matching (8 = size(cdata,1) ~= length(xData) = 4).

Error in matlab2tikz>drawImage (line 2061)
        [m2t, str] = imageAsTikZ(m2t, handle, xData, yData, cData);

Error in matlab2tikz>handleAllChildren (line 641)
                [m2t, str] = drawImage(m2t, child);

Error in matlab2tikz>drawAxes (line 848)
    [m2t, childrenEnvs] = handleAllChildren(m2t, handle);

Error in matlab2tikz>saveToFile (line 442)
        m2t = drawAxes(m2t, relevantAxesHandle);

Error in matlab2tikz (line 338)
saveToFile(m2t, fid, fileWasOpen);
```

The reason is that x and y dimensions of the data matrix are swapped in m2t, which is easy to fix:

```patch
diff --git a/src/matlab2tikz.m b/src/matlab2tikz.m
index 4a1fda4..69ab48d 100644
--- a/src/matlab2tikz.m
+++ b/src/matlab2tikz.m
@@ -2159,7 +2159,7 @@ function [m2t, str] = imageAsTikZ(m2t, handle, xData, yData, cData)
     switch length(xData)
         case 2 % only the limits given; common for generic image plots
             hX = 1;
-        case size(cData,1) % specific x-data is given
+        case size(cData,2) % specific x-data is given
             hX = (xData(end)-xData(1)) / (length(xData)-1);
         otherwise
             error('drawImage:arrayLengthMismatch', ...
@@ -2170,7 +2170,7 @@ function [m2t, str] = imageAsTikZ(m2t, handle, xData, yData, cData)
     switch length(yData)
         case 2 % only the limits given; common for generic image plots
             hY = 1;
-        case size(cData,2) % specific y-data is given
+        case size(cData,1) % specific y-data is given
             hY = (yData(end)-yData(1)) / (length(yData)-1);
         otherwise
             error('drawImage:arrayLengthMismatch', ...
```

Apologies for not posting a proper pull request with test case.

### PR DESCRIPTION
**Pull request by egeerardyn**
This fixes #713. I also took the opportunity to refactor a bit and fix a typo.

This has been tested on R2014a, R2014b on Mac without a hickup.

### CODE REVIEW

**Comment by PeterPablo** [comment]
Did you visually inspect `ACID(92)`? Code looks good -- didn't runtime test.
I noticed another issue recently that I could not yet investigate. The output is mirrored, if the axis-vector is decreasing (`all(diff(x)<0)`). You might want to have a look at this as well, while you are working on that part of the code.

**Comment by egeerardyn** [comment]
`ACID(92)` looks fine:

screen shot 2015-08-06 at 16 22 50

Is there an issue report/MWE for the problem you mention? I can certainly look into that, but not in this PR.

**Comment by PeterPablo** [comment]
I was unable to reproduce the issue I was mentioning earlier. Once I again run into it, I will open a new issue.

**Comment by egeerardyn** [comment]
@PeterPablo Thanks :+1: (I do know we had that kind of issue before, we had some checks that for a while actually even flipped the image the wrong way; so I wouldn't be surprised if there are some edge cases that are not fully tested).

Maybe running `git blame` on the image handling section of our code might clear things up?

**Pull request merged**
