### PR TITLE
Test fix octave4

### PR DESCRIPTION
**Pull request by okomarov**
check depedencies with `apt-cache depends octave`

### CODE REVIEW

**Comment by okomarov** [comment]
@matlab2tikzBot: please test this

**Comment by okomarov** [comment]
@egeerardyn How do I test on Travis?

**Comment by egeerardyn** [comment]
Travis works automatically and otherwise you have to login on Travis and go to the build page, there is a rebuild button that looks like :leftwards_arrow_with_hook:, I think

**Comment by okomarov** [comment]
This is as far as I get: our ACID fails on line 192, at `plot(m)`.

The call that is probably causing the problem is:
```
'axes' is a function from the file /usr/local/share/octave/4.0.0/m/plot/util/axes.m line 67
    if (__is_handle_visible__ (htmp))
```

where `__is_handle_visible__`  is builtin, hence compilation of the PPA release under some OS, is buggy for (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3, travis' version.

**Comment by egeerardyn** [comment]
I don't think we need this PR anymore. Closing. Thank you a lot for your investigation in Octave/Travis/OpenBLAS history! :+1:

**Pull request closed without merging**
