### PR TITLE
Vectorize move points closer rebased

### PR DESCRIPTION
**Pull request by miscco**
This is a rebased version of PR #750, that avoids a conflict with the Octave hash table.

### CODE REVIEW

**Comment by egeerardyn** [comment]
Octave passes here :+1:

**Comment by egeerardyn** [comment]
Since all comments from #750 were addressed, I think we can merge this.

**Comment by PeterPablo** [comment]
Nice! Thank you @miscco for your effort in improving `cleanfigure()`! Hopefully you will stick around and keep on submitting pull requests :smiley:

**Comment by miscco** [comment]
Thx, i thought about expanding the code to 3D but it kind of feels like an unbearable amount of pain ;)

**Comment by okomarov** [comment]
@ Hahaha, I feel your pain :). Thanks for your contributions, really appreciated. 

I do have a suggestion thogh in the cleanfigure domain: per @egeerardyn [suggestion](https://github.com/matlab2tikz/matlab2tikz/pull/695#issuecomment-134517983) we would need a "small-value" rounder (maybe a simpler version first, without alpha). It would help with Latex memory limits and the cross-version compatibility of the testing suite.

**Comment by egeerardyn** [comment]
@miscco Indeed, thank you a lot for your hard work!

@okomarov Good suggestion. I'm going to open a ticket such that we can keep track of that one.

**Pull request merged**
