### PR TITLE
Fixed missing title when visibility is set to off

### PR DESCRIPTION
**Pull request by tomlankhorst**
Potential fix for #715

### CODE REVIEW

**Comment by tomlankhorst** [comment]
Hi Egon, in case of the bodeplot the Title of the figure is stored in an axis that has visibility set to Off. Despite the axis being set to invisible, MATLAB does show the title. Please not that this is still W.I.P. created this PR to discuss some things with you guys. 

``` MATLAB
G = tf(1,[1 1]);
H = tf([1 1], [1 1 1]);

bode(G,H);
legend('G(s)','H(s)');
t = title('Bode Test Title');

% The title
t.Parent.Title

% The visibility
t.Parent.Visible
```

**Comment by egeerardyn** [comment]
Could you comment a bit on why/how this works, because I can't really understand from your code why we need to check for presence of a title to determine whether an axes is relevant to determining the bounding box or not.

Preferably, this should be made clear in the source code.

**Comment by tomlankhorst** [comment]
You're right, this is too vague so I spent some more time to trace the problem down. The thing is, invisible axes containers are checked for visible children but not for visible titles or labels. I added this now. However, this can cause axis having no children (but a title and or label) to be processed resulting in a warning.

**Comment by egeerardyn** [comment]
See #753.

**Pull request closed without merging**
