### PR TITLE
Vectorize desicion whether a segment is visible.

### PR DESCRIPTION
**Pull request by miscco**
About 5-10% faster for a data set with 1M points.
	modified:   src/cleanfigure.m

### CODE REVIEW

**Comment by miscco** [comment]
I did vectorize the whole function, as i duplicates a massive amount of stuff. Somehow cellfun and bsxfun which were needed are not as fast as they should be.

I will try to find a better solution without a for loop over a possibly long  array

**Comment by PeterPablo** [comment]
|   Testcase |                  Name |                       OK |                                                                      Status |
| :--------- | :-------------------- | :----------------------: | :-------------------------------------------------------------------------- |
| `ACID(23)` |          `quiverplot` | :heavy_exclamation_mark: | hash e662f099377f8458f3237bc5237ce0b0 != (0cc7aef48dddc2c9075a079eaf580700) |

As such comparing the output of `ACID(23)` with and without the patch will tell you, how the behavior differs.

**Comment by egeerardyn** [comment]
Thank you for your contribution, your code looks clean, so I don't have any remarks regarding that.

There are two remarks, I do want to make:
 - You might want to start a feature branch for future pull requests instead of working directly in `develop` (See [our wiki](https://github.com/matlab2tikz/matlab2tikz/wiki/Recommended-git-workflow) for more info). In the beginning it might seem more difficult, but feature branches make many things easier to work together.
 - It seems that Octave's `quiverplot` (`ACID(23)`) fails with this. We'll have to see what happens over there.

**Comment by miscco** [comment]
Ah ok, I was searching for the error, but I do not use Octave.

**Comment by PeterPablo** [comment]
Did you run the testsuite in MATLAB? What is the output? Run `status = testHeadless(); makeTravisReport(status);`...

**Comment by miscco** [comment]
I dint run it, because there was no functional change. The result is the following:

## Unreliable tests
These do not cause the build to fail.

|   Testcase |                   Name |                       OK |                                                                      Status |
| :--------- | :--------------------- | :----------------------: | :-------------------------------------------------------------------------- |
|  `ACID(1)` |     `multiline_labels` | :heavy_exclamation_mark: | hash 21a208748863224355861184cf9910f7 != (01d4eeae27254d91a0f8316897e23e81) |
|  `ACID(6)` | `sine_with_annotation` | :heavy_exclamation_mark: | hash 995cd2a901446c59f85552d48025ba27 != (7d415c014eec35c249802eb3a3ee519e) |
| `ACID(10)` |       `peaks_contourf` | :heavy_exclamation_mark: | hash 1241fa010c4c53ab967f1e61931b596f != (77bfa3a9f07e49b9061d919551ad0a0f) |
| `ACID(16)` |              `logplot` |       :white_check_mark: |                                                                             |
| `ACID(18)` |           `legendplot` | :heavy_exclamation_mark: | hash d37d19ba36d911a0db60095db48b08ef != (746423d1c0d403421667221a6b0528bf) |
| `ACID(24)` |          `quiver3plot` |       :white_check_mark: |                                                                             |
| `ACID(34)` |                 `bars` |       :white_check_mark: |                                                                             |
| `ACID(38)` |          `subplot2x2b` |       :white_check_mark: |                                                                             |
| `ACID(40)` |        `subplotCustom` |       :white_check_mark: |                                                                             |
| `ACID(42)` |            `bodeplots` | :heavy_exclamation_mark: | hash 564a3ecdd23a7aa37a83fa7e530d82bf != (8f6cafc1771cc3a506c8fc46c15ec43e) |
| `ACID(43)` |           `rlocusPlot` |       :white_check_mark: |                                                                             |
| `ACID(48)` |          `zplanePlot2` | :heavy_exclamation_mark: | hash 4c2f1fea92ce3c969475e3f6b40f87cf != (fb3ba1a4db46c9975cd00e6da99ebe48) |
| `ACID(58)` |            `surfPlot2` | :heavy_exclamation_mark: | hash 520bba1c7a536efb15c82dfcc8ce6a23 != (eb8e6d18db994ba4a90e177bd44b5db3) |
| `ACID(94)` | `stackedBarsWithOther` |       :white_check_mark: |                                                                             |
| `ACID(97)` |     `overlappingPlots` |       :white_check_mark: |                                                                             |

## Reliable tests
Only the reliable tests determine the build outcome.
Passing tests are not shown (only failed and skipped tests).

|   Testcase |              Name |                       OK |                                                                      Status |
| :--------- | :---------------- | :----------------------: | :-------------------------------------------------------------------------- |
|  `ACID(8)` |   `peaks_contour` | :heavy_exclamation_mark: | hash 4c0f04124b13d5c12351f4875455a67d != (8885c9a4185aaca594ce5d0139aa578b) |
|  `ACID(9)` |    `contourPenny` | :heavy_exclamation_mark: | hash 1bbca20d0029e2e510eb5d7c46222ee7 != (3ee200ec93371666499d72f790ee9bb3) |
| `ACID(12)` | `double_colorbar` | :heavy_exclamation_mark: | hash 44a0d0b4b35ed634d2f2f568e51f2c8a != (6355484ba42b84205cd6a7d6de76711d) |
| `ACID(14)` |     `double_axes` | :heavy_exclamation_mark: | hash a053ed16097389ed6d6cfe6f353a46ab != (331441239c1bb077aebaf5ce8abe55f1) |
| `ACID(23)` |      `quiverplot` | :heavy_exclamation_mark: | hash 6f6723cafaf167b8e13d62f56b5a0aff != (308f4ce197791f2fd5862768e1157ca8) |
| `ACID(62)` |         `spectro` | :heavy_exclamation_mark: | hash e871a0b852a68fe12d78eead39e3de3b != (4426bb06bb44d08d016595f585fb01da) |
| `ACID(71)` |   `parameterSurf` | :heavy_exclamation_mark: | hash e64030978c54cc260847bf78a8c6ea6a != (12522a58d7e3d8dc7f4e38a0970bf047) |
| `ACID(17)` | `colorbarLogplot` |          :grey_question: |                                                                     SKIPPED |

## Test summary
Test results for m2t commit b03581af1b running with MATLAB 8.5 on Linux
 3.13.0-62-generic.

```matlab
suite = @ACID;
alltests = [1:99];
reliable = [2:5 7:9 11:15 17 19:23 25:33 35:37 39 41 44:47 49:57 59:93 95:96 98:99];
unreliable = [1 6 10 16 18 24 34 38 40 42:43 48 58 94 97];
failReliable = [8:9 12 14 23 62 71];
passUnreliable = [16 24 34 38 40 43 94 97];
skipped = [17];
```

|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    8 |    7 |    0 |    15 |
|   Reliable |   76 |    7 |    1 |    84 |
|      Total |   84 |   14 |    1 |    99 |

Build fails with 7 errors. :heavy_exclamation_mark:

However I cannot really verify what is wrong. Given that there should be no functional change is assume there will be a whitespace error. Is there a chance to diff the original and new tex file?

**Comment by egeerardyn** [comment]
Oh, but you're using MATLAB R2015a (8.5). For that we know that the test suite is not completely running well yet (see #687). I will run it on my end in R2014a/R2014b (which we currently trust).

**Comment by miscco** [comment]
Oh sorry for the noise then.

I should have actually read through all the documentation and HowTos. I promise next time ill be better :)

**Comment by egeerardyn** [comment]
Don't worry about that :smiley: We are more than happy to get contributions, those guidelines are just to help everything run smoothly in the long run.

## Test summary
Test results for m2t commit b03581af1b running with Octave 3.8.0 on Mac OS 10.10.4.

```matlab
suite = @ACID;
alltests = [1:99];
reliable = [2:5 7 9:16 19:20 22:24 28:33 35:37 39:40 42:44 46:57 59:62 64:77 79:85 87:90 93 97:99];
unreliable = [1 6 8 17:18 21 25:27 34 38 41 45 58 63 78 86 91:92 94:96];
failReliable = [23];
passUnreliable = [17 25:27 45 78];
skipped = [9 12 42:44 46:49 54 59 62 71:72 75:76 80 82 87:90 98];
```

|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    6 |   16 |    0 |    22 |
|   Reliable |   53 |    1 |   23 |    77 |
|      Total |   59 |   17 |   23 |    99 |

Build fails with 1 errors. :heavy_exclamation_mark:

## Test summary
Test results for m2t commit b03581af1b running with MATLAB 8.4 on Mac OS 10.10.4.

```matlab
suite = @ACID;
alltests = [1:99];
reliable = [2:5 7:9 11:15 17 19:23 25:33 35:37 39 41 44:47 49:57 59:93 95:96 98:99];
unreliable = [1 6 10 16 18 24 34 38 40 42:43 48 58 94 97];
failReliable = [];
passUnreliable = [];
skipped = [17];
```

|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    0 |   15 |    0 |    15 |
|   Reliable |   83 |    0 |    1 |    84 |
|      Total |   83 |   15 |    1 |    99 |

Build passes. :white_check_mark:

## Test summary
Test results for m2t commit b03581af1b running with Octave 3.8.0 on Mac OS 10.10.4.

```matlab
suite = @ACID;
alltests = [1:99];
reliable = [2:5 7 9:16 19:20 22:24 28:33 35:37 39:40 42:44 46:57 59:62 64:77 79:85 87:90 93 97:99];
unreliable = [1 6 8 17:18 21 25:27 34 38 41 45 58 63 78 86 91:92 94:96];
failReliable = [23];
passUnreliable = [17 25:27 45 78];
skipped = [9 12 42:44 46:49 54 59 62 71:72 75:76 80 82 87:90 98];
```

|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    6 |   16 |    0 |    22 |
|   Reliable |   53 |    1 |   23 |    77 |
|      Total |   59 |   17 |   23 |    99 |

Build fails with 1 errors. :heavy_exclamation_mark:

So it seems that only Octave is acting up :+1: I will have a look at what happens.

**Comment by okomarov** [comment]
As a side note, I do not observe speed ups with:
```
x = linspace(0,2*pi,5e6);
y = sin(x);
h = plot(x,y);
tic
cleanfigure
toc
```
which I expected since most of the time is spent by the opheim simplification. 

Just to be clear, this does not mean I am against the PR.

**Comment by miscco** [comment]
Hey, I have realised my previous attempts at speeding up the function were overcomplicated and tried a simple approach. The new function is now 4 times faster than the old one

I have squashed the commits, how can i resend them ?

**Comment by okomarov** [comment]
@miscco For that you might need to submit a whole new PR. However, it is not advisable to re-submit a new PR with cleaner commits in this case. We will lose trace of all the feedback collected here for a seemingly cleaner commit history, which is not prefererable.

Also, be aware, that if you are testing the code with my snippet, you need to re-create the figure at each time! Otherwise, you will be cleaning a clean figure already. In other words, it is unlikely to have a 4x speedup on portion of code that is not responsible for the bottleneck.

**Comment by egeerardyn** [comment]
@miscco : That's one of the reasons to not use the `develop` branch for working in :wink: 

I would also suggest to file a new PR, and I wouldn't worry about squashing your commits (unless some of the code doesn't "compile") in the future.

Since you probably have some code in the tip of your own `develop` branch, the way to move forward is:
```bash
git checkout -b cleanfigure-vectorize
git push origin
# file your pull request again here, but for the branch "cleanfigure-vectorize"
```

Even though @okomarov doesn't find any speedup, I like in this PR that the code is more MATLAB-like (i.e. more vectorized) and that is enough by itself (supposing that it doesn't actually slow down that part).

**Comment by miscco** [comment]
Yes inhindsight, this would have been better ;) So far i only used git in a very limited fashion. Even better to learn something new. This PR can be closed, i will resubmit tomorrow.

**Comment by egeerardyn** [comment]
@miscco If you are having any trouble with `git`, please don't hesitate to ask for help. Some of us have been using it for years: in the beginning it can be daunting, but it's a really great and powerful tool. I'm looking forward to your PR tomorrow :+1:

**Pull request closed without merging**
