### PR TITLE
fix legend entry alignment

### LINKED ISSUE #654: Alignment of legend entries
```
h = plot(magic(4),'LineWidth',3);
legend(h([2,4]), 'line 2','and line 4')
title('legend entries should be aligned left')
```
Entries should be aligned left.
image

**Note:** HG1/HG2 is not affected.

### PR DESCRIPTION
**Pull request by PeterPablo**
fixes #654
[octave manual](http://octave.sourceforge.net/octave/function/legend.html)

```
h = plot(magic(3),'LineWidth',3);
title('legend entries should be properly aligned')
h = legend ({'short', 'very very long'}, 'location', 'east');
legend ('left');
```
image

MATLAB is not affected by this codepath.

### CODE REVIEW

**Comment by egeerardyn** [comment]
:+1:

**Comment by PeterPablo** [comment]
whoops, didn't notice this one has issues merging. Thanks for taking care of it!

**Comment by egeerardyn** [comment]
@PeterPablo It were some hashes that differed (that's one of the downsides of storing those hashes in the repo, but it's better than the alternatives for the moment).

**Comment by PeterPablo** [comment]
:-/ Unfortunately that hash-mismatch resolving made the other PRs choke as well. I hope you can deal with those in the same manner.

**Comment by egeerardyn** [comment]
Yeah, that's not a problem. It just has to be done locally (which is how I merge most of the time anyway, except when the commits are trivial changes).

**Comment by PeterPablo** [comment]
Probably it's best to first review #653 which could currently be merged without conflicts and afterwards continue here.

**Pull request merged**
