### PR TITLE
fix testGraphical()

### LINKED ISSUE #664: ACID(21) zoom: warning: division by zero
Executing `ACID(21)` in octave yields many `warning: division by zero` and might crash octave (and thus `testGraphical()`).
Tested on 37d139129f59ba73273ad3826b0a7e59856326db.

### PR DESCRIPTION
**Pull request by PeterPablo**
For `testGraphical()` and octave:
* also output to eps; `make clean` would otherwise delete `reference` data
* remove unecessary `pause`
* always use `gnuplot` backend

Discussion in #649.

Remaining issue, but was present before: `ACID(21)`  might crash octave (even after fixed #664).

### CODE REVIEW

**Comment by PeterPablo** [comment]
I updated the first comment slightly to reflect the current situation on `ACID(21)`.

**Comment by PeterPablo** [comment]
This can be reviewed and does not involve hashes.

**Comment by PeterPablo** [comment]
hm, it's unfortunate that you don't receive proper output using EPS. For me it's the other way round. Currently I don't get any output at all.
For now I will cherry-pick my two commits in order to test the graphical output of octave.

**Comment by egeerardyn** [comment]
I agree this is very unfortunate. Perhaps we should parametrize that part, such that we can define what picture format to use: EPS, PDF, PNG, ... and then both of us can work happily by changing a switch :-)

**Comment by PeterPablo** [comment]
Sounds like a reasonable workaround. :-)

**Comment by egeerardyn** [comment]
I'll close this here, since this is really related to an old topic, i.e. #326. I'll add it to the 2.0 milestone such that we keep an eye on this.

**Pull request closed without merging**
