### PR TITLE
add support for normalized units in Matlab figures

### PR DESCRIPTION
**Pull request by jcmonteiro**
This PR should solve #819 and #340.

I ran the tests using runMatlab2TikzTests and got the same output as the one in the develop branch:

```
|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    2 |   13 |    0 |    15 |
|   Reliable |   45 |   44 |    1 |    90 |
|      Total |   47 |   57 |    1 |   105 |
```

### CODE REVIEW

**Comment by egeerardyn** [comment]
Thank you for your pul request. 

I don't think this does everything for normalized units, because (if I remember correctly), those units are normalized with respect to the container of the object.
I.e. an axis with normalized width = 0.5 spans half the figure, a figure with normalized width = 0.5, spans half the screen (or even half the desktop possibly on a multi-screen setup, I reckon). 

While this is already an improvement (it handles those situations in some cases, but not everywhere), I think it would be better to either implement the full thing (which means passing in the handle of the object into that function, writing a function to find the parent, doing the conversion) or at least keeping some kind of warning that the conversion might be incorrect.

Because I don't think either issue can be closed as-is.

**Comment by jcmonteiro** [comment]
Oh, I didn't know that the normalized units option worked like this. In the way I implemented it, I guess the conversion is only going to work when converting a figure.

Do you think passing the handle, using this piece of code if it points to a figure, and otherwise issuing a warning is enough to get this PR merged?

**Comment by egeerardyn** [comment]
As far as I'm concerned, that's fine indeed. But you might need to change quite a bit of code to pass in those handles. In any case; as long as it keeps warning the users that the conversion is not perfect, it's fine by me :-)

**Comment by jcmonteiro** [comment]
Closing since it's been years since I looked into this one

**Pull request closed without merging**
