### PR TITLE
Cleanfigure vectorize prune outside box

### PR DESCRIPTION
**Pull request by miscco**
This is a small attempt to vectorize pruneOutsideBox. 

The new code is much clearer and easier to understand. It should also be much faster, but I believe the cleanup should be sufficient alone.

As always i have some travis tests fail on MATLAB2015a#

# MATLAB 8.5 (Linux 3.13.0-62-generic) commit 47dee78b12 

## Unreliable tests
These do not cause the build to fail.

|   Testcase |                   Name |                       OK |                                                                      Status |
| :--------- | :--------------------- | :----------------------: | :-------------------------------------------------------------------------- |
|  `ACID(1)` |     `multiline_labels` | :heavy_exclamation_mark: | hash 21a208748863224355861184cf9910f7 != (01d4eeae27254d91a0f8316897e23e81) |
|  `ACID(6)` | `sine_with_annotation` | :heavy_exclamation_mark: | hash 995cd2a901446c59f85552d48025ba27 != (7d415c014eec35c249802eb3a3ee519e) |
| `ACID(10)` |       `peaks_contourf` | :heavy_exclamation_mark: | hash 1241fa010c4c53ab967f1e61931b596f != (77bfa3a9f07e49b9061d919551ad0a0f) |
| `ACID(16)` |              `logplot` |       :white_check_mark: |                                                                             |
| `ACID(18)` |           `legendplot` | :heavy_exclamation_mark: | hash 30905e01d2507e5902023eabf9fc1466 != (746423d1c0d403421667221a6b0528bf) |
| `ACID(24)` |          `quiver3plot` |       :white_check_mark: |                                                                             |
| `ACID(34)` |                 `bars` |       :white_check_mark: |                                                                             |
| `ACID(38)` |          `subplot2x2b` |       :white_check_mark: |                                                                             |
| `ACID(40)` |        `subplotCustom` |       :white_check_mark: |                                                                             |
| `ACID(42)` |            `bodeplots` | :heavy_exclamation_mark: | hash ca7b2029a08a2a311a94b73339e2128a != (8f6cafc1771cc3a506c8fc46c15ec43e) |
| `ACID(43)` |           `rlocusPlot` | :heavy_exclamation_mark: | hash a8718c58cf1281e70f4e96d99aee2a6b != (f372b9a4004fa45ac96a21014656e143) |
| `ACID(48)` |          `zplanePlot2` | :heavy_exclamation_mark: | hash 4c2f1fea92ce3c969475e3f6b40f87cf != (fb3ba1a4db46c9975cd00e6da99ebe48) |
| `ACID(58)` |            `surfPlot2` | :heavy_exclamation_mark: | hash 520bba1c7a536efb15c82dfcc8ce6a23 != (eb8e6d18db994ba4a90e177bd44b5db3) |
| `ACID(94)` | `stackedBarsWithOther` |       :white_check_mark: |                                                                             |
| `ACID(97)` |     `overlappingPlots` |       :white_check_mark: |                                                                             |

## Reliable tests
Only the reliable tests determine the build outcome.
Passing tests are not shown (only failed and skipped tests).

|   Testcase |              Name |                       OK |                                                                      Status |
| :--------- | :---------------- | :----------------------: | :-------------------------------------------------------------------------- |
|  `ACID(8)` |   `peaks_contour` | :heavy_exclamation_mark: | hash 4c0f04124b13d5c12351f4875455a67d != (8885c9a4185aaca594ce5d0139aa578b) |
|  `ACID(9)` |    `contourPenny` | :heavy_exclamation_mark: | hash 1bbca20d0029e2e510eb5d7c46222ee7 != (3ee200ec93371666499d72f790ee9bb3) |
| `ACID(12)` | `double_colorbar` | :heavy_exclamation_mark: | hash 44a0d0b4b35ed634d2f2f568e51f2c8a != (6355484ba42b84205cd6a7d6de76711d) |
| `ACID(14)` |     `double_axes` | :heavy_exclamation_mark: | hash a053ed16097389ed6d6cfe6f353a46ab != (331441239c1bb077aebaf5ce8abe55f1) |
| `ACID(15)` |    `double_axes2` | :heavy_exclamation_mark: | hash ec8ccb7d178fd3e0227fd2cf3b210fa0 != (739edbf88cbf57187bea11ef93ebbf9a) |
| `ACID(21)` |            `zoom` | :heavy_exclamation_mark: | hash 4e56ddac18eea72b1a36166429fe8153 != (817b9999d832dc238b89573037cabc81) |
| `ACID(23)` |      `quiverplot` | :heavy_exclamation_mark: | hash 6f6723cafaf167b8e13d62f56b5a0aff != (308f4ce197791f2fd5862768e1157ca8) |
| `ACID(62)` |         `spectro` | :heavy_exclamation_mark: | hash e871a0b852a68fe12d78eead39e3de3b != (4426bb06bb44d08d016595f585fb01da) |
| `ACID(71)` |   `parameterSurf` | :heavy_exclamation_mark: | hash e64030978c54cc260847bf78a8c6ea6a != (12522a58d7e3d8dc7f4e38a0970bf047) |
| `ACID(76)` |       `myBoxplot` | :heavy_exclamation_mark: | hash ab5f495d4d03978ef42dd184d86be9a3 != (ce07c42d9618f6eff69392c66c668c82) |
| `ACID(17)` | `colorbarLogplot` |          :grey_question: |                                                                     SKIPPED |

## Test summary
Test results for m2t commit 47dee78b12 running with MATLAB 8.5 on Linux
 3.13.0-62-generic.

```matlab
suite = @ACID;
alltests = [1:99];
reliable = [2:5 7:9 11:15 17 19:23 25:33 35:37 39 41 44:47 49:57 59:93 95:96 98:99];
unreliable = [1 6 10 16 18 24 34 38 40 42:43 48 58 94 97];
failReliable = [8:9 12 14:15 21 23 62 71 76];
passUnreliable = [16 24 34 38 40 94 97];
skipped = [17];
```

|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    7 |    8 |    0 |    15 |
|   Reliable |   73 |   10 |    1 |    84 |
|      Total |   80 |   18 |    1 |    99 |

Build fails with 10 errors. :heavy_exclamation_mark:

I checked all of the reliable tests and only Test 8 produces a different image (looks like shifted by a pixel). This is especially surprising as it seems the test doesnt even enter pruneOutsideBox o.O At least I cant set a break point there.

### CODE REVIEW

**Comment by egeerardyn** [comment]
@miscco Could you re-pull against `develop` instead?

**Comment by miscco** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Yes, allready on it

Mondays...


Am 24.08.2015 um 09:17 schrieb Egon Geerardyn:
> @miscco Could you re-pull against `develop` instead?
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/matlab2tikz/matlab2tikz/pull/741#issuecomment-13407
0255
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQIcBAEBAgAGBQJV2sUlAAoJECEwb8zWbvHCTHQP/jOPTI2RR/d9efW2+75UPpYJ
IiN+8stDKM5rd3HN7U9jGfLm8j5O6xvfVXWmofO2KeYPBGUxNi/GU5Fox2iDr+tC
J0QbzvyH1PrIdzCalQuD0qF9r7kVN22rlDIJA7E/6LIhXAj+XIcKFGYI9Agzn0ov
4lNxMIxo8oFCjWE2GYZAneUmPzubwiENz1v4TB7FfZuX2aDR3v+Hy4Tq1BIkt/Wm
rIMwdMtEX3zcTo40pEXcxkAl5tVIMQs5JuDHevuaVjWWrY921teRPzqg4SE7+cCt
k1lx/HGXL5WcFfOigECF2ydc2BvY7bIW5VXXrM0iNpjXk4qQhUmSbnl3+CgBMyG0
Yjb8lR4f+YssoKmDWEU/QmZpZjCmbNYbbMo5dKy8t8ycT8LBlPHKLyoUiwhSIYDM
kmIm/F66I9OlJgmkvgOFzXRXVSH/CnNtPa4j/b8rqBWezhZpFHdpnRJlh6GqbzAF
4Yiby7rG73oD3S8Yn3RodemWjKFyox/h6+qfn2ARda47xW7D0vj+LyOgrteM7u54
cqk5jbJZTcpNx9nxWItt2OfBDszAFldXJoTQJwTEXi/Z7oTbibJiYF4KpsxUSgle
cJx7dRUaQjQ5TNZSGkE6VbRQCfqig5eoEo/yh382SWMEJJudsEzxnkLtBPA/CTw2
Y+6+PveVKMLpWkA9kjr5
=u7A5
-----END PGP SIGNATURE-----

**Comment by egeerardyn** [comment]
Don't worry. It's really an annoyance (I also have to think about changing the branch every time, but it's a necessary evil since otherwise we provide our general userbase with possibly unstable code).

**Comment by miscco** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Argh WTF.

i forgot to checkout to develop before commiting...

Have to do it again.. grml

I need more coffee

Am 24.08.2015 um 09:20 schrieb Egon Geerardyn:
> Don't worry. It's really an annoyance (I also have to think about
> changing the branch every time, but it's a necessary evil since
> otherwise we provide our general userbase with possibly unstable
> code).
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/matlab2tikz/matlab2tikz/pull/741#issuecomment-13407
0638
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQIcBAEBAgAGBQJV2sYeAAoJECEwb8zWbvHCwgkP/1wsgfOwcaY1/jJ7zdUCPtWd
zlIFZuFfOh6s0Yu3TlqeJMtBtXtE7ZZAUQ8GiGQlR30Un8r95ND2qCe6CyyTC79r
ieqYRF5ZblPMHwqI0LvdxNbvI3m1fvfibJHyDMg5QBdM7Rk2I0Q9hH8Jfipwb2ji
SqbAElx2ZocKctduP24JP98zMwCSxC7JH/OtcQkJed6RARAGCnOAb5joOy35H5tV
tvJyvSZQovIMi3KiNyy1ztAww9rSTffhkfbfIsuOPrApI14eiv3e9X9PEMBo626B
xCZCSic3GlGvVEL5Tnhsvz6gdGhEMZMrtmO+1KpIRCE04p71JZ7K/qosMGYxdU8d
DT6hkQKlU766RLYNSNMvoDmL/9wwwnObqpRfXOELp4dyGsxuwaYCslOIc2sAujwX
e/2wSFmBn7mfmHBwkm4RUWs32Cn+ikk/7wJvWdBgs1lact2ri2eNmFiF8WmpASTR
wt+778OSw1LRNoKr4Ac++Jw7gR19KVLaq5AbiH8L60r43/YifsU2iFxDwPRbCBrs
IsYNCRS9Px0N7f2kuMTstE/jZlUhs+AN/khlutq5CpoR+DFL/FctbWcF0xIXHju4
cNEo248lt2fmlG3zpH2lwWbgv4rlmcQbhHuVv/b7jZYuf7dLwXJQg9ix8Qn4YdpG
BsyiLKpJ5YLd0Y9SiLFN
=cr7y
-----END PGP SIGNATURE-----

**Comment by miscco** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I dont even know what to say. It seems that github reset the branch agai
n.


Damnt it. Finaly in the 4th attempt manage to get it right.

Im off for a coffee

Am 24.08.2015 um 09:20 schrieb Egon Geerardyn:
> Don't worry. It's really an annoyance (I also have to think about
> changing the branch every time, but it's a necessary evil since
> otherwise we provide our general userbase with possibly unstable
> code).
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/matlab2tikz/matlab2tikz/pull/741#issuecomment-13407
0638
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQIcBAEBAgAGBQJV2slzAAoJECEwb8zWbvHC09wQAJq1OzOLHtT1QwxzSFjo5Wv+
tWAbUUcll1CkOkFDGBDNr6p6yFu03sXcNFt+mVUD26fUOVOgrJEYDJz2cPaMiQiF
7wVnxpsOCloC74VsjM3R0eRzoqEnfgLZOH9PxYaOeDfDni7is/AdcSHQBSoOGAHw
qCL2DxFBOOZdeLsBHc3NmJ0YqdD+A+CqrGDhhROVkMDl7fpGL6EdmOe41tv1Wp5S
OfjQh/3SLHv0dY0ebrDh/hQKhQbGG23YZTaDYPvSkE9TMA8ndnuUHtTp1QXuouXQ
vZUgV4pOfLwS2uw9WJ8NTyzWNVJGGaXsRQKeq/aPqpvFw4t08GCr+ASKejG43+/K
2Dl8bnA3/NWyi8BM7koO2EwYvRUlftnaaUyQJ4HXBoBlh+w7Mt4sab/tea4rJ1Tb
h0iw2WpfDp6WF4GGNz9BxJwr9Z83Uj+Ky986Zsl7prrPZhy+qQJ4BOIzHKxcMUut
jhO2XahWyQXOMg8IlfHuDMYOrCkkt+CW2VFOiFEVvdcOkpbJC2ACr4QRH8ov0BP6
DHHtJYNfH3oCNTavUfYUAk2d4RFu28fhJGIgQvw8EJUZBpiWEWVa0y4HZaL0BvJu
fpEUzCrOouJ2ZuWIjmJHLztUPRlrx0kGF76HiNyXMcDFR5RQAB+x9zPgb7o6xPdP
tc5WnNWnv8I95jM3i1ku
=UcKu
-----END PGP SIGNATURE-----

**Comment by egeerardyn** [comment]
GitHub will always set the branch to pull against to `master`, indeed. Huge PITA (well, it would be better if The MathWork could serve the GitHub releases instead of the `master` branch). Nico and I have asked them to look into this, but I don't expect those changes will be implemented soon.

**Pull request closed without merging**
