### PR TITLE
Simplification

### PR DESCRIPTION
**Pull request by egeerardyn**
This partly addresses #391. So no new features here, mostly refactorings, although I did some tiny changes here and there (see commit messages in those cases).

Statistics:

          Function          |Complexity 
----------------------------|-----------
        `drawPatch`         |    22     
`matlabTicks2pgfplotsTicks` |    19     
     `drawScatterPlot`      |    18     
    `getColorbarOptions`    |    15     
   `shaderOptsSurfPatch`    |    14     
     `getMarkerOptions`     |    13     
       `drawContour`        |    13     
      `drawBarseries`       |    12     
  `findLegendInformation`   |    11     
         **Total**          |    137  

complexity

Each commit has been tested with R2014b. The whole changeset (i.e. everything until f31dd72) has been tested with R2014a as well. For the Octave part, I rely on Travis.

### CODE REVIEW

**Comment by okomarov** [comment]
Except from my comments to the single commits I agree on everything else. I add a couple of points:
* I am aware of `drawPatch` being complex and I can look into semplifying it. I recall thinking of a couple of methods before.
* Can we get rid of `drawStemSeries` and `drawStairSeries` which respectively simply call `drawStemOrStairSeries_(m2t, h, 'ycomb');` and `drawStemOrStairSeries_(m2t, h, 'const plot');`, and use those calls in the switch statement of `drawHggroup`?

**Comment by egeerardyn** [comment]
@okomarov Thanks for reviewing my changes. I agree with most of your comments and will adapt accordingly. For the other things, I hope we can find a consensus. If not, I'm willing to revert those changes.

I'm a bit hesitant to remove `drawStemSeries` and `drawStairSeries` since those actually tell what is being done and encapsulate part of the `pgfplots` details (i.e. that the plot type is a `const plot` or `ycomb`). Having those inside `drawHgGroup` mixes the levels of abstraction, that is: HgGroup has nothing to do with those `pgfplots` concepts and I think we should keep that separation. Your observation that these functions do very little themselves is very correct, but allows for that separation of concerns.

**Comment by PeterPablo** [comment]
By looking at the code I could not identify (potential) issues. As such I am fine with the changes and will have another brief look, as soon as you remove the wip label.

**Comment by egeerardyn** [comment]
I consider this done, except maybe for a clear consensus on 63a3e66 and a3f8447?

**Comment by okomarov** [comment]
For me it's good to go.

**Pull request merged**
