### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by egeerardyn**
Further TODOs here (for me):

 - [x] run graphical tests in HG1 / R2014a
 - [x] run graphical tests in HG2 / R2014b
 - [x] run graphical tests in Octave 3.8
 - [x] run graphical tests in Octave 4.0
 - [x] check differences between current `master` and this PR
 - [x] discuss the differences

### CODE REVIEW

**Comment by egeerardyn** [comment]
| Environment | Before | After |
|----------------|--------|-------|
| MATLAB 2014a (HG1) | [HG1-before.pdf](https://github.com/matlab2tikz/matlab2tikz/files/416244/HG1-before.pdf) | [HG1-after.pdf](https://github.com/matlab2tikz/matlab2tikz/files/416245/HG1-after.pdf) |
| MATLAB 2014b (HG2) | [HG2-before.pdf](https://github.com/matlab2tikz/matlab2tikz/files/416247/HG2-before.pdf) | [HG2-after.pdf](https://github.com/matlab2tikz/matlab2tikz/files/416248/HG2-after.pdf) |
| Octave 3.8 | [Oct38-before.pdf](https://github.com/matlab2tikz/matlab2tikz/files/416249/Oct38-before.pdf) | [Oct38-after.pdf](https://github.com/matlab2tikz/matlab2tikz/files/416250/Oct38-after.pdf) | 
| Octave 4.0 | no reference figures | no reference figures |

In some cases, I had to mess a bit with everything to get it to compile: remove some test from the runner, copy in dummy PDFs, ...

**Comment by miscco** [comment]
@egeerardyn I will try to have a look at this during the weekend. Is there any reason, why there are merge conflicts?. Would it make sense to combine the 3 plots into the pdf, e.g. have reference 1.0 and 1.1 in one page?

**Comment by egeerardyn** [comment]
The merge conflicts are in README, if I see it correctly. I will merge those manually when we come to the actual release.

Having all the figures side-by-side would make sense, however, that might be a feature for a next release (perhaps with the outstanding PR of Oleg)

**Comment by egeerardyn** [comment]
@matlab2tikzBot: please test this

**Comment by egeerardyn** [comment]
Okay, I think I will go ahead and merge this bugger: it has been tested for quite a while, I think there might be some minor regressions, but also a lot of improvements that should finally get out there in the mainline.

**Comment by PeterPablo** [comment]
Great news! Thank you for your effort!

**Comment by egeerardyn** [comment]
It was long overdue :smile: but finishing the PhD and starting a new job takes quite a bit of energy.

**Comment by miscco** [comment]
Yeah, thanks for finally finishing this big piece of work. I add a toddler to the mix, so I hope, that i can finally breath again next year.

**Comment by egeerardyn** [comment]
@miscco I don't have any personal toddler experience, but I believe that indeed those things take some time.

In any case, m2t is a for-fun project, so no obligations/hard feelings whatsoever if you prioritize your family (that is the healthy choice).

**Pull request merged**
