### PR TITLE
octave: use delfun of a legend to infer if hasLegend

### LINKED ISSUE #607: Octave legend incorrectly detects all entries
```
h = plot(magic(3));
legend(h(2), 'straight line')
```
capture

### PR DESCRIPTION
**Pull request by okomarov**
Fixes #607 (Octave legend incorrectly detects all entries)

### CODE REVIEW

**Comment by PeterPablo** [comment]
Travis is pretty unhappy about your change:
```
error: matrix cannot be indexed with {
error: called from:
error:   /home/travis/build/matlab2tikz/matlab2tikz/test/../src/matlab2tikz.m at line 727, in function matlab2tikz>findLegendInformation
```

May be [here](https://github.com/matlab2tikz/matlab2tikz/pull/608/files#diff-76782b0b358b916574ab8ad22a7ce6fbR727) square brackets need to be used? Why `6` anyhow?

**Comment by PeterPablo** [comment]
@okomarov, did you see my comment?

**Comment by okomarov** [comment]
Why is travis not running for last commit?

**Comment by PeterPablo** [comment]
Reopening is probably easiest. I would have suggested merging current `develop`, but you already did that.

**Pull request closed without merging**
