### PR TITLE
FIX #587 -- pipe character and interpreter tex

### LINKED ISSUE #587: the sign "| should be in mathmode at least for the y-axis
There may be a trick that I did not find but this example gives me the sign "|" in the wrong orientation
```
%Matlab
figure, plot([1:10],[1:10])
ylabel('|abs|')
matlab2tikz('myplot.tex')
```

```
%Latex
\documentclass{article}
\usepackage{pgfplots}
\usepackage{tikz}
\begin{document}
\begin{figure}
\input{myplot.tex}
\end{figure}
\end{document} 
```

### PR DESCRIPTION
**Pull request by PeterPablo**
Let's see how I have to update the hashes...

### CODE REVIEW

**Comment by PeterPablo** [comment]
:+1: Travis happy -- are you developers too?

**Comment by okomarov** [comment]
Next time, please include in the description of the PR the issue, so that it's clickable :sweat_smile:

**Comment by PeterPablo** [comment]
It's clickable in the first commit, displayed below the PR message. I will obey your wish the next time.

**Comment by okomarov** [comment]
Right, sorry :)

**Pull request merged**
