### PR TITLE
Line simp reliable

### PR DESCRIPTION
**Pull request by PeterPablo**
Clean pull request for **line simp** with removed superfluous commits (of mine).
Needs:
- [x] hashes for MATLAB
- [x] fix trailing whitespace
- [x] verification by somebody else that hashes are now reliable

Fix for reliable hashes was determined in #659.
(Potential) successor of #645.
Does not need #641 for reliable octave tests.

The last few commits do:
* incorporate current tip of `develop`
* cherry-pick #655 to fix herrorbarplot in octave
* adapt `herrorbarPlot` (ACID(74)) to have changing horizontal/vertical deviations
* simplify handling of errorbars, as suggested by @okomarov 
* update hashes
* tests run reliable locally and on Travis due to specifying both `W` and `H` explicitly

Status:
* [x] octave: ok
* [x] R2014a: ok
* [x] R2014b: missing annotations in 87,89,90 are tracked in #658
* [x] output is compileable with `pdflatex`, due to the fine job of the new line simplification (good for my environment, where the `1.12 pgfplots` wrongly determines my `lua` as outdated -- [fixed](https://sourceforge.net/p/pgfplots/bugs/84/) by Christian Feuersänger)

### CODE REVIEW

**Comment by PeterPablo** [comment]
Alright -- I hope it was worth the effort. Somebody else please give this a try. Thanks.

**Comment by PeterPablo** [comment]
I rechecked the graphical output of octave and all is well. (Failing tests 81 and 83 are fixed by PR #657 #656.)

**Comment by PeterPablo** [comment]
I merged `upstream/develop`. Travis is green.

**Comment by egeerardyn** [comment]
On R2014b, I cannot confirm your results:

```
The following tests are known to be unreliable. They, however, do not cause the build to fail.

           ACID(  1) multiline_labels         : hash 914722e4c88bbb14f637b98f568e9196 != (3a7f9dc3baa956d37f48de440a0a5c8c)
           ACID(  6) sine_with_annotation     : hash 939f916e437708224fb46b162774412f != (a59fd3dad1567f590bd1cce6c2d158d9)
           ACID(  9) contourPenny             : OK
           ACID( 10) peaks_contourf           : hash df292939dc0c9a6e7999795b3b41a538 != (e96d5d45d18712532daa68a344f0a440)
           ACID( 12) double_colorbar          : hash d27ce6a62e1ffa415575cb6acc94e1cd != (86f5f24792a2f60f788815c7d0fc9556)
           ACID( 16) logplot                  : hash abc60dd4344bdb611d59da4f4aa0982d != (f54c7491ec3c26dcbf88cc572436dc97)
           ACID( 17) colorbarLogplot          : SKIPPED
           ACID( 18) legendplot               : hash 11d39dcd176326c7f931b74cb1e867b1 != (13e19dea4881b4d8dbbf98aadc6375ff)
           ACID( 20) moreLegends              : hash da07759193d0ea6502b6c8c5d6716d9d != (114da9956c2f75c8d2a80d1cdb3a8cff)
           ACID( 24) quiver3plot              : hash be662bed35ba46b60e8e37d3ed27b6d7 != (b0c97f834a0361021f1eee62b09edc57)
           ACID( 34) bars                     : hash e4c8ea6e0d90c330728f4909a382f11f != (d85ca6286f7643b97fcfe57f87d4021b)
           ACID( 36) errorBars                : hash d947dab08d432c8ed7cf1ea85484ccd3 != (a39fb9ccb71ec344517fabf695257239)
           ACID( 38) subplot2x2b              : hash 7ce836b8631aeb64429ddd8570cefb70 != (ddbc242a51a5a88cb5ef607e141fe2f0)
           ACID( 39) manualAlignment          : hash 239a9d1f6af2a8a5637f9fb75eb36922 != (231f7927bfa7e3029ad7e3d39693906a)
           ACID( 40) subplotCustom            : hash ce334159804b1869c285b858e89f8028 != (486c0970a8b707cd7a680fdfc0182856)
           ACID( 45) besselImage              : hash 8c7ea17c04f1dee3adfaea8a4b7345d9 != (93dfb58352905df1fbf73d1678eff78d)
           ACID( 47) zplanePlot1              : hash 12ffa2e783efbe219cd30382808bfb8a != (5c3c2599d56e66416163af3c176748ac)
           ACID( 48) zplanePlot2              : hash 1ea3e572e37963ec051bb94c30a401a8 != (6ace0ad1c7552bbf896d2ecbcb89d3c6)
           ACID( 49) freqResponsePlot         : hash 52585eb5be9372ffa89abedebf227102 != (8146b0e417d01e59bddb2598ca024cbd)
           ACID( 52) multipleAxes             : OK
           ACID( 57) surfPlot                 : hash e5733c90b5362b185fc59671c92a89ae != (1932eeadafa742b56e83c5662af1272c)
           ACID( 58) surfPlot2                : hash 12427459fa7838eadba75ba242a24b40 != (ef92d7ab0a3891011a75000b763a7089)
           ACID( 61) ylabels                  : hash 30572ccebb62be472ff317b73461c11c != (76d201824a30f36b3fbe8b796b6d354e)
           ACID( 63) mixedBarLine             : OK
           ACID( 66) textext                  : hash c72dc12d1a4ea8874eb13b1f2284b57e != (a7d42c336b9453d01920743af865c04f)
           ACID( 67) texrandom                : OK
           ACID( 68) latexInterpreter         : hash f9e51784e285cc3bdafb261d941bcf78 != (26fc5650abb30d9c38293f87c6947696)
           ACID( 73) rectanglePlot            : hash 586afabcaa039cdf397d1a58e9626488 != (2069bc16ff640c4476afb8b305212088)
           ACID( 88) annotationSubplots       : hash fd5ef76551a5b35a2f2993a2adfb93ce != (940a17b3bf32b84abd566228ef707d98)
           ACID( 90) annotationTextUnits      : hash 4920648c5d16de5ad62f5491d3b1ebab != (585836070b68d698236badbc05c4dbe6)
           ACID( 91) imageOrientation_PNG     : OK
           ACID( 92) imageOrientation_inline  : OK
           ACID( 94) stackedBarsWithOther     : hash b4962346da2c5e574ef02b677c9abaaa != (391673d9eb634f34d32ae3f25c163cb9)
           ACID( 95) colorbarLabelTitle       : OK
           ACID( 96) textAlignment            : hash 42e2ec6f8df5d992419dfe754ba65795 != (d8608dbcbcefa5f27bfdb99959948282)
           ACID( 97) overlappingPlots         : hash 741fccfff4f52e7a1d92cc5fa59c9401 != (56ded8061ced6b4c273cf09ca180a2d9)

 28 of  36 tests failed. :-( 


Only the following tests determine the build outcome:
           ACID(  2) plain_cos                : hash 254765475fb64a72a4bf4288988174db != (5941d29b92160cff4392c067bbc21990)
           ACID(  3) sine_with_markers        : OK
           ACID(  4) markerSizes              : OK
           ACID(  5) markerSizes2             : OK
           ACID(  7) linesWithOutliers        : hash 6add41e81f7a3036042792c3ff993db1 != (8da18a00a4bfa8f112826f96487fded1)
           ACID(  8) peaks_contour            : OK
           ACID( 11) many_random_points       : OK
           ACID( 13) randomWithLines          : hash dbe9b29796129c55850d8048fc361ec7 != (9ad7de751e28e7ffe3518fd83543b412)
           ACID( 14) double_axes              : OK
           ACID( 15) double_axes2             : hash 5f695c2398efc10db86d2e659d3b6c14 != (a8d0b273d6690ec01fc595938c19c63b)
           ACID( 19) legendplotBoxoff         : OK
           ACID( 21) zoom                     : OK
           ACID( 22) quiveroverlap            : hash a32b7bde9de0ccd62d9f48bb3b3b6fa2 != (6dfa4bf96cf0764cf241fd37e9e617bd)
           ACID( 23) quiverplot               : hash d7e5ca878c297485d79c7fdd6a92ec4e != (2436ebe3f35bd7a39398a3e0d89a0e45)
           ACID( 25) logicalImage             : OK
           ACID( 26) imagescplot              : OK
           ACID( 27) imagescplot2             : OK
           ACID( 28) stairsplot               : hash 3603e55388786f35b564ea5422b43d66 != (29440a1dc8b8fee95fd91f39c5206589)
           ACID( 29) polarplot                : OK
           ACID( 30) roseplot                 : hash 356aad19c9b2893e42fa982d1ccec0ef != (3f97d916253426014582999e1d4778c5)
           ACID( 31) compassplot              : hash d7f4181cca73042ea9e8ca9a0944560a != (32a2714d7b1b0417a5d6e9ba76e0336b)
           ACID( 32) stemplot                 : hash b41cfec41aaa0f4f5fc37f2775187386 != (0a3b98102d8a941a303b427329327900)
           ACID( 33) stemplot2                : hash baa69434364669c14c592cffaa9c469c != (31ac69a2100a420571eba925fb1385f0)
           ACID( 35) xAxisReversed            : hash d110adc82f6489f94917ccafeb0c51a2 != (f1e11872b019ab2e3cd66202ae8a414f)
           ACID( 37) errorBars2               : OK
           ACID( 41) legendsubplots           : OK
           ACID( 42) bodeplots                : hash 09c59799a1790ce49cfd3b36826dbd57 != (f0c6a278a0303ce11147ede574b61340)
           ACID( 43) rlocusPlot               : hash 1abd12c0602542fd5f3b5c477783e10d != (ed48ac9fa7dc0e423eadfcd4e53e2887)
           ACID( 44) mandrillImage            : OK
           ACID( 46) clownImage               : OK
           ACID( 50) axesLocation             : hash 3ae9cd9edf8b3ff2d46f594cbe1e9a86 != (7dc1d379e18e2cbe16fa228c921d2ea3)
           ACID( 51) axesColors               : hash b30a83133a3d4785ac79e85457306601 != (62b8d24ae88ad1df29ed94ff50818f36)
           ACID( 53) scatterPlotRandom        : OK
           ACID( 54) scatterPlot              : OK
           ACID( 55) scatter3Plot             : OK
           ACID( 56) spherePlot               : OK
           ACID( 59) superkohle               : OK
           ACID( 60) meshPlot                 : OK
           ACID( 62) spectro                  : OK
           ACID( 64) decayingharmonic         : hash c0675d69b5966282e319d1c11ffa7dd0 != (6d0f2f1f3da6b8831a31dd4dca7340a9)
           ACID( 65) texcolor                 : OK
           ACID( 69) latexmath2               : OK
           ACID( 70) parameterCurve3d         : hash 2df6f224f80d5880511bbba7a4467e4a != (cc56f7b519dea88270d14ea58a652e85)
           ACID( 71) parameterSurf            : hash 8ddaacbb7b6b87beda5db9f7874d254d != (b3d93b3a3ae8498629dd665f20a989b9)
           ACID( 72) fill3plot                : OK
           ACID( 74) herrorbarPlot            : OK
           ACID( 75) hist3d                   : OK
           ACID( 76) myBoxplot                : OK
           ACID( 77) areaPlot                 : OK
           ACID( 78) customLegend             : OK
           ACID( 79) pixelLegend              : hash cf0ab1497c44f7f57faeb6d94eafb36d != (7d79797477f188f2727092d682372a37)
           ACID( 80) croppedImage             : OK
           ACID( 81) pColorPlot               : OK
           ACID( 82) hgTransformPlot          : OK
           ACID( 83) scatterPlotMarkers       : OK
           ACID( 84) multiplePatches          : OK
           ACID( 85) logbaseline              : OK
           ACID( 86) alphaImage               : OK
           ACID( 87) annotationAll            : hash 471ba0dbd079663f4414c0b9b810d46e != (25343a4fffc0dfe12f289ba29e0cd7f0)
           ACID( 89) annotationText           : hash d49dd77f23d88e63042460d01b599ce1 != (078649b0d43e91119480957c2d64bcc3)
           ACID( 93) texInterpreter           : OK
           ACID( 98) histogramPlot            : hash 04c8b0bc8254effd2bbc6c7b380249ed != (de2083405bca245fc2f8d641893cf49a)
           ACID( 99) alphaTest                : OK

 23 of  63 tests failed. :-( 
```
Anyhow, I think to make sure that the 1.0 release is not delayed too much, the line simplification stuff is not our top priority right now (and I wonder whether it makes sense to always run `cleanfigure` in our test suite). In the long run, it's probably clearer and cleaner to just call that in the test cases that require it.

**Comment by PeterPablo** [comment]
I ran into the same issue and this is what motivated me to implement global state mocking. The issue that different environments produce different output is due to how `cleanfigure()` simplifies the plots, which is mainly dependent on `ScreenPixelsPerInch`, if I remember correctly.
Strangely I have an issue with the hashes anyhow. I will update them shortly. May be I messed up https://github.com/matlab2tikz/matlab2tikz/commit/850c3a3754d3e33844ab894db48ac9f47957e7cf.

**Comment by PeterPablo** [comment]
@egeerardyn, please have another look. From my POV dea2fe440dec388045fbe20a8650f5e9c154ce02 is critical as it is needed to ensure uniform behavior on different environments. I would not remove `cleanfigure` from the testsuite execution, if we aren't forced to. My impression is that we can reach stable hash generation, even with `cleanfigure()`.

**Comment by PeterPablo** [comment]
We need to choose on how to proceed (https://github.com/matlab2tikz/matlab2tikz/pull/660#commitcomment-11368809). @egeerardyn, please advice. I will then adapt the PR, merge `develop` and update the hashes.

**Comment by PeterPablo** [comment]
Just saw that #683 will update all hashes. So let's wait with merging here, until I review #683, again merged `develop` and updated the hashes.

**Comment by PeterPablo** [comment]
@egeerardyn you might anyhow already check, if everything else is in good shape here, as updating the hashes is not a big deal (as an incremental final review step).

**Comment by PeterPablo** [comment]
@egeerardyn, please review

**Comment by egeerardyn** [comment]
## Octave 3.8.2 Mac

```
The following tests are known to be unreliable. They, however, do not cause the build to fail.

           ACID(  1) multiline_labels         : hash 52ab19fa2f495a2c18f85fe9828595cf != (beda5969f833f85342c1ac49c66ba84f)
           ACID(  6) sine_with_annotation     : hash 47d74378c28bc13c252802ccf4f59ed2 != (b006a77663744393abb03a470d6cbab5)
           ACID(  8) peaks_contour            : hash 10f2b9bc1b7f88583a5ec6dac1954d79 != (7d1a67eb06d87860adca396396e576cd)
           ACID( 17) colorbarLogplot          : OK
           ACID( 18) legendplot               : OK
           ACID( 21) zoom                     : OK
           ACID( 25) logicalImage             : OK
           ACID( 26) imagescplot              : OK
           ACID( 27) imagescplot2             : OK
           ACID( 34) bars                     : OK
           ACID( 38) subplot2x2b              : OK
           ACID( 39) manualAlignment          : OK
           ACID( 41) legendsubplots           : OK
           ACID( 45) besselImage              : OK
           ACID( 56) spherePlot               : OK
           ACID( 58) surfPlot2                : OK
           ACID( 63) mixedBarLine             : hash ddd1440395b1249570205c5a6affc2e1 != (d104e14ad08f82223ef6e7bfb0251fcd)
           ACID( 67) texrandom                : hash 415132f269c392174996f417e4adb80d != (fb8664a711c774c7dc79fd591492d1b8)
           ACID( 78) customLegend             : OK
           ACID( 83) scatterPlotMarkers       : plot failed
           ACID( 86) alphaImage               : OK
           ACID( 91) imageOrientation_PNG     : OK
           ACID( 92) imageOrientation_inline  : OK
           ACID( 94) stackedBarsWithOther     : OK
           ACID( 95) colorbarLabelTitle       : OK
           ACID( 96) textAlignment            : hash 000b946a520c4fd0fd0feef6e54427e1 != (ab67c21b9a17cb4fc55cf2b112977581)

  7 of  26 tests failed. :-( 


Only the following tests determine the build outcome:
           ACID(  2) plain_cos                : hash 0747cb87b25ffe4eeea0ba10e6aac21e != (3b30b1eeadd6fe04c8ffac2b5e75bff0)
           ACID(  3) sine_with_markers        : OK
           ACID(  4) markerSizes              : OK
           ACID(  5) markerSizes2             : OK
           ACID(  7) linesWithOutliers        : OK
           ACID(  9) contourPenny             : SKIPPED
           ACID( 10) peaks_contourf           : OK
           ACID( 11) many_random_points       : OK
           ACID( 12) double_colorbar          : SKIPPED
           ACID( 13) randomWithLines          : OK
           ACID( 14) double_axes              : OK
           ACID( 15) double_axes2             : OK
           ACID( 16) logplot                  : OK
           ACID( 19) legendplotBoxoff         : OK
           ACID( 20) moreLegends              : OK
           ACID( 22) quiveroverlap            : OK
           ACID( 23) quiverplot               : OK
           ACID( 24) quiver3plot              : OK
           ACID( 28) stairsplot               : OK
           ACID( 29) polarplot                : OK
           ACID( 30) roseplot                 : OK
           ACID( 31) compassplot              : OK
           ACID( 32) stemplot                 : OK
           ACID( 33) stemplot2                : OK
           ACID( 35) xAxisReversed            : OK
           ACID( 36) errorBars                : OK
           ACID( 37) errorBars2               : OK
           ACID( 40) subplotCustom            : OK
           ACID( 42) bodeplots                : SKIPPED
           ACID( 43) rlocusPlot               : SKIPPED
           ACID( 44) mandrillImage            : SKIPPED
           ACID( 46) clownImage               : SKIPPED
           ACID( 47) zplanePlot1              : SKIPPED
           ACID( 48) zplanePlot2              : SKIPPED
           ACID( 49) freqResponsePlot         : SKIPPED
           ACID( 50) axesLocation             : OK
           ACID( 51) axesColors               : OK
           ACID( 52) multipleAxes             : OK
           ACID( 53) scatterPlotRandom        : OK
           ACID( 54) scatterPlot              : SKIPPED
           ACID( 55) scatter3Plot             : OK
           ACID( 57) surfPlot                 : OK
           ACID( 59) superkohle               : SKIPPED
           ACID( 60) meshPlot                 : OK
           ACID( 61) ylabels                  : OK
           ACID( 62) spectro                  : SKIPPED
           ACID( 64) decayingharmonic         : OK
           ACID( 65) texcolor                 : OK
           ACID( 66) textext                  : OK
           ACID( 68) latexInterpreter         : OK
           ACID( 69) latexmath2               : OK
           ACID( 70) parameterCurve3d         : OK
           ACID( 71) parameterSurf            : SKIPPED
           ACID( 72) fill3plot                : SKIPPED
           ACID( 73) rectanglePlot            : OK
           ACID( 74) herrorbarPlot            : OK
           ACID( 75) hist3d                   : SKIPPED
           ACID( 76) myBoxplot                : SKIPPED
           ACID( 77) areaPlot                 : OK
           ACID( 79) pixelLegend              : OK
           ACID( 80) croppedImage             : SKIPPED
           ACID( 81) pColorPlot               : OK
           ACID( 82) hgTransformPlot          : SKIPPED
           ACID( 84) multiplePatches          : OK
           ACID( 85) logbaseline              : OK
           ACID( 87) annotationAll            : SKIPPED
           ACID( 88) annotationSubplots       : SKIPPED
           ACID( 89) annotationText           : SKIPPED
           ACID( 90) annotationTextUnits      : SKIPPED
           ACID( 93) texInterpreter           : OK
           ACID( 97) overlappingPlots         : OK
           ACID( 98) histogramPlot            : SKIPPED
           ACID( 99) alphaTest                : OK

  1 of  73 tests failed. :-( 
```

## MATLAB 
*will soon follow*

**Comment by egeerardyn** [comment]
:+1:

**Pull request merged**
