### PR TITLE
Fix legend entries for filled contours

### LINKED ISSUE #582: Contour plot introduces legend issue
Tested on R2014b, on current `develop` head.

**Code**
```
contourf(peaks(10), 3);
colorbar();
colormap(jet);
hold on;
h(1)=plot(1:10,1:10,'r');
h(2)=plot(1:10,sin(1:10)+5,'b');
legend(h,'red','blue')
```

** Result**
image

**Should be**
image

**Solution**
The tex code should contain `forget plot` for the contour's `\addplot` instructions. Since they are 
missing, the legend is missing the linestyle of the blue and red plot.

### PR DESCRIPTION
**Pull request by okomarov**
Fixes #582 (Contour plot introduces legend issue).

Uses `maybeShowInLegend`

### CODE REVIEW

**Comment by PeterPablo** [comment]
Is this done in an ACID test? If yes, please link the issue (if no, adapt an ACID test). I know, that the code path won't be checked (at the moment) due to HG2. But let's prepare for the future ;-)
Apart from that :+1:

**Comment by PeterPablo** [comment]
@okomarov, I am wondering why isn't the hash of `peaks_contourf()` affected? (I did not actually run the code.)

**Comment by PeterPablo** [comment]
image

Is this the expected output?
Here is the tex-code: https://gist.github.com/PeterPablo/641da8a66adca68bda70

**Comment by okomarov** [comment]
This PR is only about HG2, but can look into HG1 and fix that too :)

**Comment by PeterPablo** [comment]
*HG2:*
image

Looks good! Why didn't you change the hash? I get 19a39a81083ad7c44ba43c7695639c3c on R2014b.

**Comment by egeerardyn** [comment]
@okomarov: Doesn't `pgfplots` have its own legend definition for contour plots. If so, we should use that in the long run. However, I think that the display format currently depends on the internal data structure  in MATLAB (which seems to differ between HG1 and HG2), which is fine by me for the time being.

**Comment by okomarov** [comment]
@egeerardyn No, pgfplots has `mesh` type but not contour. We used 'area legend' in HG1 since it was plotting the patches and we can stick with that.

**Comment by PeterPablo** [comment]
Please restore `superkohle` hash.
`textext` hash gives a mismatch. Please mark this test as unreliable.
`contourPenny` gives a mismatch. Please mark this test as unreliable. see https://github.com/matlab2tikz/matlab2tikz/issues/615#issuecomment-92420501

`testHeadless(8)` fails on R2014a with:
```
error: Error using hg.text/get
The name 'Faces' is not an accessible property for an instance of class 'text'.
error: MATLAB:class:InvalidProperty
error: called from:
error:   ~/matlab/0_addons/figures/matlab2tikz/src/matlab2tikz.m at line 1788, in function drawPatch
...
```

Output of ACID(10) `contourf` is very good now (tested graphically). Octave still show the additional legends:
image

@okomarov, do you want to work on this in the scope of this PR? If not, please file an issue.

**Comment by okomarov** [comment]
@PeterPablo Octave cannot be fixed in a clean way (and not in this PR in any case) since the contour is an hggroup, but it has not tag saying so. The workaround would be to implement a `guessType()` function only for Octave hggroups that would try/catch to get properties unique to specific plots and hence infer the type. 

I will restore the hashes.

@egeerardyn I reckon we need to modify `saveHashTable()` default bahaviour to keep a pre-existing hash if the test was not executed (see sparkhole test problem above).

**Comment by egeerardyn** [comment]
@okomarov I agree with your observation. The current behavior of `saveHashTable` is not a perfect fit for our use. I will create a separate issue report to discuss this further.

**Comment by okomarov** [comment]
@egeerardyn I am in 475a629904aa601c3cd37c3dabf14a726dca7d19 and have problems with hashes generation in Octave on Linux VM. 

Running `a = testHeadless()`, returns for test 28
```matlab
a{28}
ans =

  scalar structure containing the fields:

    description = A simple stairs plot.
    function = stairsplot
    testsuite = @ACID
    index =  28
    issues = [](0x0)
    unreliable = 0
    skip = 0
    closeall = 0
    extraOptions = {}(0x0)
    extraCleanfigureOptions = {}(0x0)
    plotStage =

      scalar structure containing the fields:

        message =
        error = 0
        fig_handle =  2

    saveStage =

      scalar structure containing the fields:

        message =
        error = 0

    tikzStage =

      scalar structure containing the fields:

        message =
        error = 0
        texFile = data/converted/test28-converted.tex
        pdfFile = data/converted/test28-converted.pdf

    hashStage =

      scalar structure containing the fields:

        message =
        error = 0
        expected = fe8de0a0482d579c2436c719d81913cf
        found = fe8de0a0482d579c2436c719d81913cf

    elapsedTime =  0.32518
```
while 

```matlab
ans =
{
  [1,1] =

    scalar structure containing the fields:

      description = A simple stairs plot.
      function = stairsplot
      testsuite = @ACID
      index =  28
      issues = [](0x0)
      unreliable = 0
      skip = 0
      closeall = 0
      extraOptions = {}(0x0)
      extraCleanfigureOptions = {}(0x0)
      plotStage =

        scalar structure containing the fields:

          message =
          error = 0
          fig_handle =  1

      saveStage =

        scalar structure containing the fields:

          message =
          error = 0

      tikzStage =

        scalar structure containing the fields:

          message =
          error = 0
          texFile = data/converted/test28-converted.tex
          pdfFile = data/converted/test28-converted.pdf

      hashStage =

        scalar structure containing the fields:

          message = error: The hash "0b1e95d55fc0704f43e5c1d4e12e3e03" does not match the reference hash "fe8de0a0482d579c2436c719d81913cf"

          error =  1
          expected = fe8de0a0482d579c2436c719d81913cf
          found = 0b1e95d55fc0704f43e5c1d4e12e3e03

      elapsedTime =  0.30731

}
```

**Comment by egeerardyn** [comment]
@okomarov 
I don't quite follow where `ans` is set in the second fragment. If you can provide a MWE, to reproduce the behavior, I will try to look at it.

**Comment by okomarov** [comment]
```
a = testHeadless();
a{28}
```

versus

`testHadless(28)`

**Comment by egeerardyn** [comment]
@okomarov I get 
```
{
  [1,1] =

    scalar structure containing the fields:

      description = A simple stairs plot.
      function = stairsplot
      testsuite = @ACID
      index =  28
      issues = [](0x0)
      unreliable = 0
      skip = 0
      closeall = 0
      extraOptions = {}(0x0)
      extraCleanfigureOptions = {}(0x0)
      plotStage =

        scalar structure containing the fields:

          message = 
          error = 0
          fig_handle =  1

      saveStage =

        scalar structure containing the fields:

          message = 
          error = 0

      tikzStage =

        scalar structure containing the fields:

          message = 
          error = 0
          texFile = data/converted/test28-converted.tex
          pdfFile = data/converted/test28-converted.pdf

      hashStage =

        scalar structure containing the fields:

          message = error: The hash "0b1e95d55fc0704f43e5c1d4e12e3e03" does not match the reference hash "fe8de0a0482d579c2436c719d81913cf"

          error =  1
          expected = fe8de0a0482d579c2436c719d81913cf
          found = 0b1e95d55fc0704f43e5c1d4e12e3e03

      elapsedTime =  0.34675

}
```

for both cases (except for a different run time). Can you verify your first result to make sure?

**Comment by okomarov** [comment]
Yes, I still confirm this behaviour.

Apart from that I get ton of

```
warning: delete: no such file: data/converted/test95-converted.tex
error: /usr/lib/x86_64-linux-gnu/octave/3.8.2/oct/x86_64-pc-linux-gnu/__magick_read__.oct: failed to load: /usr/lib/x86_64-linux-gnu/octave/3.8.2/oct/x86_64-pc-linux-gnu/__magick_read__.oct: undefined symbol: _ZN6Magick5ColorC1Ehhh
error: called from:
error:   /usr/share/octave/3.8.2/m/image/private/__imwrite__.m at line 198, in function __imwrite__
error:   /usr/share/octave/3.8.2/m/image/imwrite.m at line 112, in function imwrite
error:   /media/sf_github/matlab2tikz/src/matlab2tikz.m at line 2102, in function matlab2tikz>imageAsPNG
```

Maybe, you can suggest a way to re-install Octave in a different way than that used by Travis?

**Comment by PeterPablo** [comment]
So which linux OS are you on now? How did you install octave?
I usually run the following command after setting up the path:
`status = testHeadless(); nErrors = makeTravisReport(status);` followed by `saveHashTable(hashes)`, if needed.

Your last comment indicates that m2t can't write out any output file. Do you have write access? Has this ever worked for you?

**Comment by PeterPablo** [comment]
Another thing: Did you `diff` the output of the generated tex file for both cases? Or wasn't the output even written to the `data` directory? The hash is calculated on the file's content before it is written out to the disc. The actual data though might give a hint as to what is going wrong.

**Comment by okomarov** [comment]
I diffed and there was no difference, which might suggest that data is not written to the directory. I will check if it is an issue with VM and shared directory. In the meantime if someone could update hashes this pr is ready.

Sent from my iPhone

On 7 May 2015, at 21:02, "Peter Pablo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Another thing: Did you diff the output of the generated tex file for both cases? Or wasn't the output even written to the data directory? The hash is calculated on the file's content before it is written out to the disc. The actual data though might give a hint as to what is going wrong.

**Comment by PeterPablo** [comment]
I could calculate the hashes tomorrow morning. Should I then create a PR on your repositroy? I still haven't figured out how to contribute to a PR, whose originating branch is in somebody else's repository.

Please run m2t in a directory of the VM first to rule out permission problems. `make distclean` in `test/tex` beforehand makes it easy to delete all previous test run data.

**Comment by PeterPablo** [comment]
I was about to generate the hashes and wondered why the hash of ACID(28) changes:
image

As you see, it has an extra legend. This will be fixed by #619 it seems.

--
Furthermore, the issue reported in #582 is not fixed in octave and now testcase covers this:
image

@okomarov, what exactly do you think is fixed? (What are the test steps?) Would you please be so kind and adapt an ACID test to cover the issue described in #582? Thank you!

By the way, the new hash for ACID(28) on octave for me also is `stairsplot : 0b1e95d55fc0704f43e5c1d4e12e3e03`. HG1 and HG2 are unchanged -- as expected.

**Comment by okomarov** [comment]
@PeterPablo This PR has a Matlab tag and as I said before, basically Octave cannot be fixed. 

I probably won't have time, I barely manage to skim through the notifications and yesterday I wasted most of it trying to figure out the hash problem.

**Comment by PeterPablo** [comment]
Sorry, I got confused since by your recent octave *hash* issues. I still wonder why that octave hash changed thoug...

**Comment by PeterPablo** [comment]
@okomarov, as I said I don't know how to push directly to this PR, since the branch is in your repository. Update the hash of octave's stairsplot to `0b1e95d55fc0704f43e5c1d4e12e3e03` and I'll hit merge.

**Comment by egeerardyn** [comment]
@PeterPablo I will guide you through the process in chat

**Pull request closed without merging**
