### PR TITLE
HG2 Fix for legend box off bug

### LINKED ISSUE #609: HG2 legend box off bug
```
plot(1:2)
legend a 
legend boxoff
```

capture

In Matlab HG2, the 'box', 'off' property is not translated correctly.

### PR DESCRIPTION
**Pull request by okomarov**
Fixes #609 (HG2 legend box off bug)

### CODE REVIEW

**Comment by PeterPablo** [comment]
Same here: Code looks good :+1: 
Please reference an ACID test that covers this and if needed adapt an existing test (or introduce a new test) that covers (all) the legend options. Thank you!

**Comment by egeerardyn** [comment]
:+1:

**Comment by PeterPablo** [comment]
May I ask you to restore the hash of `superkohle` -- you might have accidentally deleted it, since you don't have the needed toolbox. After that, feel free to merge yourself.

Apart from that the tests run fine. I tested HG 1, HG 2 and octave, just to be on the save side. I visually compared the output of HG1 and HG2 of `legendplotBoxoff` and noticed that the legend is not placed in different corners, already in MATLAB. We should inspect that test, see #628.

**Comment by PeterPablo** [comment]
Friendly ping @okomarov. Simply restore hash of `superkohle` and merge.

**Pull request closed without merging**
