### PR TITLE
Make table

### PR DESCRIPTION
**Pull request by okomarov**
Print by column.
Tested on ACID and graphically it does not affect the output but the alignment of the elements in the table are not backward compatible, and hence most hashes fail.

Please, **test for speed** and then we can decide what to do with alignment.

### CODE REVIEW

**Comment by egeerardyn** [comment]
Using R2014b on Mac OS X, I see only a tiny difference between both (and I wonder whether it's significant).
Maybe, the problem in #562 is not our code per se, but rather something MATLAB-OS X related?
At home, I will have a go at it on a Linux install (but I have to reinstall MATLAB there).

test                       |    before (2c2ab10)    |    after (3f9999b) 
---------------------------|-------------:|-----------:
multiline_labels           |    0.87s     |    1.43s
plain_cos                  |    0.31s     |    0.39s
sine_with_markers          |    0.29s     |    0.43s
markerSizes                |    0.27s     |    0.33s
markerSizes2               |    1.62s     |    1.88s
sine_with_annotation       |    0.45s     |    0.94s
linesWithOutliers          |    0.25s     |    0.38s
peaks_contour              |    0.60s     |    0.86s
contourPenny               |    3.70s     |    2.55s
peaks_contourf             |    0.93s     |    1.39s
many_random_points         |    0.77s     |    0.84s
double_colorbar            |    2.51s     |    2.99s
randomWithLines            |    0.40s     |    0.67s
double_axes                |    0.37s     |    0.58s
double_axes2               |    0.31s     |    0.41s
logplot                    |    0.33s     |    0.41s
legendplot                 |    1.39s     |    1.45s
legendplotBoxoff           |    0.61s     |    0.70s
moreLegends                |    0.74s     |    0.84s
zoom                       |    1.17s     |    1.38s
quiveroverlap              |    0.30s     |    0.56s
quiverplot                 |    1.71s     |    1.87s
quiver3plot                |    0.42s     |    0.46s
logicalImage               |    0.29s     |    0.64s
imagescplot                |    0.31s     |    0.30s
imagescplot2               |    0.34s     |    0.26s
stairsplot                 |    0.33s     |    0.34s
polarplot                  |    1.72s     |    1.98s
roseplot                   |    1.08s     |    1.23s
compassplot                |    2.44s     |    1.34s
stemplot                   |    0.60s     |    0.63s
stemplot2                  |    0.48s     |    0.54s
bars                       |    1.30s     |    1.66s
xAxisReversed              |    0.51s     |    0.66s
errorBars                  |    0.28s     |    0.41s
errorBars2                 |    0.30s     |    0.42s
subplot2x2b                |    0.43s     |    0.68s
manualAlignment            |    4.00s     |    3.04s
subplotCustom              |    0.51s     |    0.81s
legendsubplots             |    1.03s     |    2.15s
bodeplots                  |    1.27s     |    3.25s
rlocusPlot                 |    0.81s     |    1.37s
mandrillImage              |    0.30s     |    0.36s
besselImage                |    0.50s     |    0.69s
clownImage                 |    0.30s     |    0.38s
**zplanePlot1**                |    **48.66s**    |    **41.83s**
zplanePlot2                |    1.90s     |    2.35s
**freqResponsePlot**           |    **15.60s**    |    **15.48s**
axesLocation               |    0.40s     |    0.47s
axesColors                 |    0.35s     |    0.40s
multipleAxes               |    0.76s     |    0.81s
scatterPlotRandom          |    0.52s     |    0.60s
scatterPlot                |    0.68s     |    0.65s
scatter3Plot               |    2.26s     |    1.69s
spherePlot                 |    2.37s     |    1.91s
surfPlot                   |    2.03s     |    1.88s
surfPlot2                  |    0.95s     |    1.04s
superkohle                 |    2.47s     |    3.06s
meshPlot                   |    1.72s     |    1.88s
ylabels                    |    1.52s     |    1.49s
spectro                    |    3.28s     |    3.07s
mixedBarLine               |    0.52s     |    0.83s
decayingharmonic           |    1.13s     |    1.25s
texcolor                   |    0.25s     |    0.33s
textext                    |    0.29s     |    0.32s
texrandom                  |    0.80s     |    1.63s
latexInterpreter           |    0.42s     |    0.42s
latexmath2                 |    0.31s     |    0.47s
parameterCurve3d           |    0.86s     |    1.14s
parameterSurf              |    0.99s     |    1.10s
fill3plot                  |    0.50s     |    0.56s
rectanglePlot              |    0.28s     |    0.36s
herrorbarPlot              |    0.76s     |    0.82s
hist3d                     |    2.43s     |    2.06s
myBoxplot                  |    0.59s     |    1.80s
areaPlot                   |    0.43s     |    0.63s
customLegend               |    0.40s     |    0.47s
pixelLegend                |    0.60s     |    0.59s
croppedImage               |    0.42s     |    0.41s
pColorPlot                 |    0.60s     |    0.54s
hgTransformPlot            |    3.12s     |    2.32s
scatterPlotMarkers         |    0.83s     |    0.90s
multiplePatches            |    0.35s     |    0.47s
logbaseline                |    0.27s     |    0.34s
alphaImage                 |    0.31s     |    0.57s
annotationAll              |    0.64s     |    1.35s
annotationSubplots         |    0.81s     |    0.77s
annotationText             |    0.79s     |    0.89s
annotationTextUnits        |    0.86s     |    0.92s
imageOrientation_PNG       |    0.80s     |    0.80s
imageOrientation_inline    |    0.87s     |    0.89s
texInterpreter             |    0.34s     |    0.35s
stackedBarsWithOther       |    0.93s     |    0.90s
colorbarLabelTitle         |    0.60s     |    0.69s
textAlignment              |    0.51s     |    0.49s
overlappingPlots           |    0.78s     |    0.75s
histogramPlot              |    0.41s     |    0.78s

**Comment by okomarov** [comment]
Thanks for testing. The `num2str()` could indeed pay off only with a big table and is in fact doing poorly with the faster tests. If, after investigating, `makeTable()` is still the bottleneck I have in mind a way to avoid `num2str()` but still print by column.

**Comment by okomarov** [comment]
@egeerardyn If you get a chance to re-test, I would appreciate (I get a considerable speedup)

**Comment by egeerardyn** [comment]
@okomarov: Here it's slightly better, but just slightly in 83d2a78:

> multiline_labels done (3.02s).
> plain_cos done (0.69s).
> sine_with_markers done (0.45s).
> markerSizes done (0.55s).
> markerSizes2 done (1.99s).
> sine_with_annotation done (0.74s).
> linesWithOutliers done (0.31s).
> peaks_contour done (0.78s).
> contourPenny done (2.22s).
> peaks_contourf done (1.42s).
> many_random_points done (0.80s).
> double_colorbar done (2.34s).
> randomWithLines done (0.56s).
> double_axes done (0.35s).
> double_axes2 done (0.51s).
> logplot done (0.35s).
> legendplot done (1.05s).
> legendplotBoxoff done (0.52s).
> moreLegends done (0.70s).
> zoom done (1.44s).
> quiveroverlap done (0.56s).
> quiverplot done (1.66s).
> quiver3plot done (0.73s).
> logicalImage done (0.70s).
> imagescplot done (0.30s).
> imagescplot2 done (0.33s).
> stairsplot done (0.48s).
> polarplot done (1.94s).
> roseplot done (1.23s).
> compassplot done (1.23s).
> stemplot done (0.61s).
> stemplot2 done (0.70s).
> bars done (1.68s).
> xAxisReversed done (0.53s).
> errorBars done (0.43s).
> errorBars2 done (0.35s).
> subplot2x2b done (0.46s).
> manualAlignment done (2.81s).
> subplotCustom done (0.49s).
> legendsubplots done (1.13s).
> bodeplots done (4.04s).
> rlocusPlot done (0.92s).
> mandrillImage done (0.39s).
> besselImage done (0.79s).
> clownImage done (0.29s).
> **zplanePlot1 done (39.66s).**
> zplanePlot2 done (4.53s).
> **freqResponsePlot done (15.58s).**
> axesLocation done (1.06s).
> axesColors done (0.32s).
> multipleAxes done (0.70s).
> scatterPlotRandom done (0.50s).
> scatterPlot done (0.65s).
> scatter3Plot done (1.71s).
> spherePlot done (2.09s).
> surfPlot done (1.80s).
> surfPlot2 done (0.79s).
> superkohle done (3.24s).
> meshPlot done (1.77s).
> ylabels done (1.69s).
> spectro done (3.17s).
> mixedBarLine done (0.68s).
> decayingharmonic done (0.98s).
> texcolor done (0.31s).
> textext done (0.34s).
> texrandom done (0.66s).
> latexInterpreter done (0.46s).
> latexmath2 done (0.61s).
> parameterCurve3d done (1.89s).
> parameterSurf done (1.01s).
> fill3plot done (0.46s).
> rectanglePlot done (0.32s).
> herrorbarPlot done (0.75s).
> hist3d done (1.52s).
> myBoxplot done (1.14s).
> areaPlot done (0.82s).
> customLegend done (0.54s).
> pixelLegend done (0.64s).
> croppedImage done (0.48s).
> pColorPlot done (0.55s).
> hgTransformPlot done (2.32s).
> scatterPlotMarkers done (0.84s).
> multiplePatches done (0.38s).
> logbaseline done (0.36s).
> alphaImage done (0.35s).
> annotationAll done (1.44s).
> annotationSubplots done (0.73s).
> annotationText done (0.91s).
> annotationTextUnits done (1.01s).
> imageOrientation_PNG done (0.77s).
> imageOrientation_inline done (0.87s).
> texInterpreter done (0.39s).
> stackedBarsWithOther done (1.04s).
> colorbarLabelTitle done (0.71s).
> textAlignment done (0.57s).
> overlappingPlots done (0.80s).
> histogramPlot done (0.86s).

**Comment by okomarov** [comment]
:disappointed:

**Comment by okomarov** [comment]
I added two commits which are a minimalistic intervention where I remove the `cellfun()`. If it makes a big difference, I would issue a new cleaner PR with only those two commits.

**Pull request closed without merging**
